### ISSUE TITLE
Release files is not new

### ISSUE THREAD

**Issue by lwintermelon** [Calysto/octave_kernel#102]
![image](https://user-images.githubusercontent.com/18533670/30873917-63c69aa6-a321-11e7-89c8-bd3207e6e161.png)
But it didnt, the latest release from pip and github didn't switch to the new install method , still containing `install.py` 
So if run `python -m octave_kernel install`, it won't work as expected ,  it seems to be equal to `ipython kernel install`! Just installed kernel spec python. It may be very confusing and the octave kernel sepc won't be installed. Better notice it in README.

**Comment by blink1073** [comment]
Apologies, I had released from an earlier commit.  I released 0.27.1 with the appropriate files/behavior.

**Comment by lwintermelon** [comment]
python wheel v0.27.1 is still the old one...

**Comment by blink1073** [comment]
Whoops again, released v0.27.2.
