### ISSUE TITLE
Can't register octave_kernel with Jupyter

### ISSUE THREAD

**Issue by Schamschula** [Calysto/octave_kernel#103]
Until https://github.com/Calysto/octave_kernel/commit/cab8ee253c61198c216ecd8bae178849b841678c I could use the old method to install the octave_kernel. Now I'm supposed to use the "metakernel standard install method," which doesn't seem to be well documented.

Bottom line: I have installed octave_kernel on a new machine, but can't get at it, as the second step, i.e. `python -m octave_kernel install` fails. A hint of how to use `--user` would also be helpful.
My old machines still can find the current octave_kernel, as everything was configured using the old install method.

I also need to fix the installation instructions for the MacPorts Portfile for py-octave_kernel, so others can install and use this.

**Comment by dsblank** [comment]
What version of metakernel and octave_kernel do you have?

**Comment by Schamschula** [comment]
I've got the following installed:
py27-metakernel version 0.20.7
py27-octave_kernel 0.27.2

**Comment by dsblank** [comment]
You are using `python setup.py to install` the Python package? You might also try using `pip` to install it. I haven't used Python2.7 for awhile. You can run jupyter with Python3 and still have a Python2 kernel, by the way. Perhaps @blink1073 has further ideas for running octave_kernel on the Mac with Python27.

**Comment by Schamschula** [comment]
I'm installing using the MacPorts infrastructure, thus I'm using `python setup.py install`. pip is not involved here.

**Comment by blink1073** [comment]
Hi @Schamschula, running `python setup.py install && python -m octave_kernel --user` installs the kernel in the same location as the old install method, `/Users/<username>/Library/Jupyter/kernels/octave`.  I'll leave this open as a note to update the readme.

**Comment by Schamschula** [comment]
I get the following error when running `/opt/local/bin/python -m octave_kernel install --user`:

`Error executing Jupiter command 'kernelspec': [Errno 2] No such file or directory`

Note: I'm explicitly calling the MacPorts installed version of python, as the macOS version has no knowledge of these modules.

**Comment by blink1073** [comment]
Okay, I think we should switch to the approach recommended [here](https://github.com/jupyter/jupyter_client/pull/235), where the kernel is automatically installed in a suitable location when the python package is installed.
