### ISSUE TITLE
View GIF in Jupyter notebook

### ISSUE THREAD

**Issue by adl1995** [Calysto/octave_kernel#105]
I wanted to know whether it's possible to view a GIF file in Jupyter notebook? There are a few workarounds for this using `IPython` as mentioned [here](https://github.com/ipython/ipython/issues/10045). Is there any equivalent for this using Octave?

For now, I have tried displaying each frame individually using `imshow()` in a `for` loop. But, it only shows a single frame.

I use this code (results are shown below):

```
for i = 1:10
    I = imread ("football-projected.gif", i);
    imshow(I);
    drawnow;
    pause(1.5);
endfor
```

![screenshot - 071017 - 14 08 58](https://user-images.githubusercontent.com/13198325/31306442-8d342764-ab69-11e7-99c4-ea4eb6a9a761.png)

**Comment by adl1995** [comment]
I resolved this using inline markdown:

![projected-football](projected-football.gif "projected-football")

Closing this issue now.

**Comment by paggers** [comment]
The link you posted above (projected-football) is dead. Could you repost? 
Cheers

**Comment by adl1995** [comment]
@paggers The GIF file is around 38MB, so I can't upload it here on GitHub. However, I only had to provide a path to the file in Markdown, like this:
`![football](data/football.gif "football")`

Hope that helps!

**Comment by iphton** [comment]
Did you try this ?

```
with open('F:/zom_pic.gif','rb') as f:
    display(Image(data=f.read(), format='gif'))
```

**Comment by gaurav-vision** [comment]
Any image format either png, jpg, jpeg or gif etc, you want to show in python jupyter notebook then simply use matplotlib library.
"import matplotlib.pyplot as plt"
"import matplotlib.image as mpimg"
img = mpimg.imread("/home/gaurav/soft computing assignment/soft computing/river.gif")
plt.imshow(img)

**Comment by hovikgas** [comment]
> Any image format either png, jpg, jpeg or gif etc, you want to show in python jupyter notebook then simply use matplotlib library.
> "import matplotlib.pyplot as plt"
> "import matplotlib.image as mpimg"
> img = mpimg.imread("/home/gaurav/soft computing assignment/soft computing/river.gif")
> plt.imshow(img)

If it is a GIF, it only shows the first frame, so it only shows up as a picture. Is there a special argument for format='gif' or something to specify?
