### ISSUE TITLE
kernel.json not  found!!

### ISSUE THREAD

**Issue by sombralibre** [Calysto/octave_kernel#106]
Hi there guys,

I've just installed octave-kernel 0.28.0 and then 0.28.1 and still getting the following error:

**FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/octave_kernel/kernel.json'**

I'm using these packages:

oct2py==3.8.1
octave-kernel==0.28.1

thanks in advance.

**Comment by blink1073** [comment]
Hi @sombralibre, can you please try `pip uninstall octave_kernel` and then `pip install octave_kernel` to make sure there is no interference?

**Comment by sombralibre** [comment]
I've rebuild all the containers layers as I do it yesterday, however now is working fine with octave-kernel==0.28.1, it's weird because yesterday it not worked with the same procedure ; anyway now it's working fine, so thanks a lot guys.

**Comment by blink1073** [comment]
Cheers.
