### ISSUE TITLE
Could not find egg.info directory in install record for octave-kernel

### ISSUE THREAD

**Issue by Ivy-Xiao** [Calysto/octave_kernel#11]
Hi. I installed IPython3 on Windows and used pip install octave_kernel in cmd. While the prompt says it's successfully installed, it has error message "Could not find egg.info directory in install record for octave-kernel", and when I open octave from IPython Notebook, it keeps crashing. I tried it again with IPython2 and the same thing happened. Would you know how to fix this? Thanks!

**Comment by blink1073** [comment]
Hi @Ivy-Xiao, thanks for the report!  Can you run `pip list` from your terminal and give me the outputs for `pip` and `octave-kernel`?

**Comment by Ivy-Xiao** [comment]
Hi Steven, thanks a lot for the prompt reply! Attached are the PrntScr of
the outputs of pip list.

**Comment by blink1073** [comment]
@Ivy-Xiao, it looks like you forgot your attachment.

**Comment by Ivy-Xiao** [comment]
![egginfo2](https://cloud.githubusercontent.com/assets/7267162/8383471/76f312e6-1bef-11e5-8635-c9ad7517f35d.jpg)
![egginfo3](https://cloud.githubusercontent.com/assets/7267162/8383472/76f3f918-1bef-11e5-82bf-cd58fce8a9be.jpg)
![egginfo1](https://cloud.githubusercontent.com/assets/7267162/8383473/76f5cc98-1bef-11e5-9716-a9b5f4547b1b.jpg)

Oops, sorry, github doesn't transfer images from gmail replies I guess.

**Comment by Ivy-Xiao** [comment]
![egginfo1](https://cloud.githubusercontent.com/assets/7267162/8383523/c19f7866-1bef-11e5-8efa-bc794ae78586.jpg)
![egginfo2](https://cloud.githubusercontent.com/assets/7267162/8383522/c19f5534-1bef-11e5-84d5-4cbe1a27b708.jpg)
![egginfo3](https://cloud.githubusercontent.com/assets/7267162/8383524/c1a0e872-1bef-11e5-8a8b-1d15665c061b.jpg)

Oops sorry, github through gmail doesn't allow image attachments I guess.

**Comment by blink1073** [comment]
Can you try the following from an IPython prompt?:

`import imp; print(imp.find_module('octave_kernel')[1])`

**Comment by Ivy-Xiao** [comment]
Yeah, I got this
\AppData\Local\Enthought\Canopy\User\lib\site-packages\octave_kernel-0.11.0-py2.7.egg\octave_kernel.py

**Comment by blink1073** [comment]
Do you have kernels in `/usr/local/share/jupyter/kernels/` or `~/.ipython/kernels`?

**Comment by MiguelAngelDiaz** [comment]
![87f8a40a6c0e8a32 1](https://cloud.githubusercontent.com/assets/1174945/9139508/9f230468-3cf8-11e5-9824-6c890e2b48f6.jpg)
Yes

**Comment by blink1073** [comment]
Closing due to lack of response, feel free to reopen.
