### ISSUE TITLE
Kernel crash on start

### ISSUE THREAD

**Issue by idahlke** [Calysto/octave_kernel#110]
I'm having some problems with the kernel crashing everytime a new notebook tries to start it. When I click new->Octave notebook, I get a little box that says "Kernel starting, please wait...". After waiting a bit the message switches to "Dead kernel". The behavior repeats _similarly_ as jupyter tries to restart the kernel.

I'm running a docker container built from jupyter/docker-stacks/scipy-notebook with some extra modules installed in the Dockerfile. The repository is public on [bitbucket](https://bitbucket.org/idahlke/jupyter-idahlke/src), with the Octave code under the dev branch.

The only install statements are below. I experimented with the second line but haven't had luck so far.
```
# Add Octave kernel
RUN pip install octave_kernel
#    python -m octave_kernel.install
```

**Comment by blink1073** [comment]
Is the `octave` executable provided by the base docker image?  The `octave_kernel` doesn't come with `octave` itself.

**Comment by idahlke** [comment]
I don't know anything about the octave executable. I followed the instructions in this repo's wiki. Do I need to grab the octave executable from elsewhere for the kernel to talk to?

**Comment by blink1073** [comment]
Please check the [readme](https://github.com/Calysto/octave_kernel#an-octave-kernel-for-jupyter) under "prerequisites"

**Comment by idahlke** [comment]
Dang it. I hate it when I've just missed an obvious instruction step. I'll add that in and retest. Thanks!

**Comment by idahlke** [comment]
Yep that solved the problem.

**Comment by blink1073** [comment]
Great!
