### ISSUE TITLE
How do I reload a function file?

### ISSUE THREAD

**Issue by CptanPanic** [Calysto/octave_kernel#111]
Using a python notebook, I can use the autoreload extension to have a file that is included reloaded in a kernel, this doesn't work for the octave notebook.  Is there a way to do this besides restarting kernel?

Thanks.

**Comment by dsblank** [comment]
For a function written in the notebook? There isn't a way in the jupyter notebook interface. In an external file? Does octave itself have such a reload function?

**Comment by blink1073** [comment]
Yep: https://octave.sourceforge.io/octave/function/rehash.html

**Comment by dsblank** [comment]
Thanks, @blink1073 ... @CptanPanic does `rehash` solve your issue?

**Comment by CptanPanic** [comment]
Yes thanks.
