### ISSUE TITLE
Hardcoded path for kernel.json prevents installation on distributed file system and local container disk

### ISSUE THREAD

**Issue by dpiparo** [Calysto/octave_kernel#112]
Hi,

first of all thanks for this nice kernel: it works quite smoothly and allows Octave to shine as interactive tool in the context of notebooks!

Here at CERN we are trying to make Octave available to the scientific and engineering community via SWAN (swan.web.cern.ch).

We are encountering an issue in the installation of the kernel. This helper function assumes that the kernel.json file sits next to the kernel.py file: https://github.com/Calysto/octave_kernel/blob/master/octave_kernel/kernel.py#L37 

This assumption might not always be true: for example in our case, we distribute via a shared fs the python code but rely on the container image to provide to jupyter the kernel (for performance reasons - the container storage is simply faster).

Would it be possible to remove this constraint, perhaps with an environment variable which is checked before erroring out?

Cheers,
    Danilo

**Comment by blink1073** [comment]
Hi @dpiparo, sure, I'd accept a PR allowing that path to be overridden with an environment variable.
