### ISSUE TITLE
Can't start the Octave kernel

### ISSUE THREAD

**Issue by estebancortero** [Calysto/octave_kernel#115]
I have the current Jupyter Notebook installed via Anaconda as well as Octave 4.2.1 on Windows 10 64x. I also installed the Octave kernel using `pip install octave_kernel`.
Unfortunately, when I start Jupyter Notebook, I still can only select Python 3 as kernel and not Octave when clicking "New".

**Comment by dsblank** [comment]
The following command shows which kernels jupyter knows about:

```bash
jupyter kernelspec list
```
It must be that the pip you used was outside of the environment that jupyter is in. Perhaps you need "pip3" or to give the full path the the anaconda pip.

**Comment by estebancortero** [comment]
```
$jupyter kernelspec list
Available kernels:
  octave     c:\program files\python36\share\jupyter\kernels\octave
  python3    c:\program files\python36\share\jupyter\kernels\python3
```
It seems like the kernel is installed correctly. But I can't create a new notebook when I select new:
![screenshot-2018-1-25 home](https://user-images.githubusercontent.com/35761012/35416333-0b4964b4-0229-11e8-9284-afc332b1a6e0.png)
