### ISSUE TITLE
Octave Kernel dies and cannot restart - Windows 10 64b

### ISSUE THREAD

**Issue by Toocgit** [Calysto/octave_kernel#121]
Hey,

I have installed Jupyter Notebook and the octave_kernel. Here are the versions of the octave_kernel and metakernel I have installed:

![image](https://user-images.githubusercontent.com/28844073/36164409-2c74f5e4-10e4-11e8-8ccc-8cfc06960039.png)

I have set-up the following user environment variable:

![image](https://user-images.githubusercontent.com/28844073/36164526-7cae3b1a-10e4-11e8-885c-7d01d31d50bb.png)

When I launch Jupyter Notebook from the Anaconda navigator and select a new notebook with the octave kernel also selected, an instance of JN opens in my web browser and then right away the octave kernel dies and cannot restart.

If I launch Jupyter Notebook from the anaconda prompt using 'jupyter console --kernel octave', I get the following feedback:

![image](https://user-images.githubusercontent.com/28844073/36164787-5edd1aa6-10e5-11e8-9ab6-b5535e41defa.png)

![image](https://user-images.githubusercontent.com/28844073/36164813-6b627672-10e5-11e8-9299-e2126db7324a.png)

Do you have advice on what the problem is?

Chris

**Comment by blink1073** [comment]
Hi @Toocgit, I believe the executable path should end with `\octave-cli.exe`.

**Comment by Toocgit** [comment]
Hi @blink1073,

I tried the following but the problem is persisting:

![image](https://user-images.githubusercontent.com/28844073/36166339-0d34ef9e-10ea-11e8-985b-c99e55212df2.png)

![image](https://user-images.githubusercontent.com/28844073/36166431-6fa10e7e-10ea-11e8-8ebe-a354c5ebbdeb.png)

![image](https://user-images.githubusercontent.com/28844073/36166566-cc2de4dc-10ea-11e8-8875-a91102a831af.png)

**Comment by blink1073** [comment]
Do you get that same `PermissionError` with the following when run in a python prompt?

```python
import os
from octave_kernel.kernel import OctaveEngine
e = OctaveEngine()
e.eval('ones(3)')
```

**Comment by Toocgit** [comment]
Yeah, here is what I got:

import os

from octave_kernel.kernel import OctaveEngine

e = OctaveEngine()
Traceback (most recent call last):

  File "<ipython-input-5-cf2058d2bf0a>", line 1, in <module>
    e = OctaveEngine()

  File "C:\Users\Christopher\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 158, in __init__
    self.repl = self._create_repl()

  File "C:\Users\Christopher\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 353, in _create_repl
    version = subprocess.check_output(version_cmd).decode('utf-8')

  File "C:\Users\Christopher\Anaconda3\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout

  File "C:\Users\Christopher\Anaconda3\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Users\Christopher\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 209, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\Christopher\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)

  File "C:\Users\Christopher\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)

PermissionError: [WinError 5] Access is denied

**Comment by blink1073** [comment]
Does the following work?

```python
import os
from subprocess import check_output
check_output(os.environ['OCTAVE_EXECUTABLE'] + ' --version')
```

**Comment by Toocgit** [comment]
Hey,

I got the following error message:

![image](https://user-images.githubusercontent.com/28844073/36263552-5c953c64-1262-11e8-9841-592c80656e0f.png)

**Comment by blink1073** [comment]
And if you change to `octave-cli.exe` in your environment variable?

**Comment by Toocgit** [comment]
I submitted my last comment too quickly, I also got the following error messages:

![image](https://user-images.githubusercontent.com/28844073/36264511-d6b2016a-1264-11e8-981a-60a0e3a01542.png)

![image](https://user-images.githubusercontent.com/28844073/36264525-e12b084e-1264-11e8-8d16-66672e69ffc0.png)

![image](https://user-images.githubusercontent.com/28844073/36264548-e9a06c08-1264-11e8-83da-955a757157a6.png)

I will try now with octave-cli.exe

**Comment by blink1073** [comment]
Are you able to launch the `octave-cli.exe` path directly from a `cmd.exe` prompt?

**Comment by Toocgit** [comment]
Sorry but I don't quite understand what you mean.

**Comment by blink1073** [comment]
I mean open a Windows Command Prompt, and then type the full path to `octave-cli.exe` followed by ` --version`.

**Comment by Toocgit** [comment]
Okay, here is what I got back:

![image](https://user-images.githubusercontent.com/28844073/36269985-842bc21a-1272-11e8-8a77-7c9300a8d089.png)

**Comment by blink1073** [comment]
I'm afraid I don't know why running it as a Python subprocess would give a different result.

**Comment by Toocgit** [comment]
It is working now!! Thank you for all of your help.

**Comment by blink1073** [comment]
Glad to hear it, cheers!

**Comment by hearaujo-hub** [comment]
what didi you do?

> It is working now!! Thank you for all of your help.

what did you do? having same problem here
