### ISSUE TITLE
%plot with format svg doesn't update

### ISSUE THREAD

**Issue by pebbe** [Calysto/octave_kernel#122]
When I run a specgram command in one cell, and then another specgram command in another cell, that second cell has the same image as the previous cell.

**Comment by pebbe** [comment]
This only happens when I start with a cell with this:
```
%plot -s 800,600 -f svg
```

**Comment by dsblank** [comment]
To be clear, it works properly in some situations? Can you say when it works correctly?

**Comment by pebbe** [comment]
This works as it should:

cell:
```
%plot -f png
```
cell:
```
pkg load signal;
Fs = 8000;
t = 0:1/Fs:1;
x = cos(2*pi*250*t) + cos(2*pi*750*t) + cos(2*pi*1250*t);
specgram(x);
```
cell:
```
Fs = 8000;
t = 0:1/Fs:1;
x = cos(2*pi*250*t) + cos(2*pi*1250*t);
specgram(x);
```

You get two spectrograms, one with three lines, one with two.

Now, change the first cell to this:
```
%plot -f svg
```
Run all cells again, and you end up with two identical spectrograms.

**Comment by pebbe** [comment]
Another problem with svg: when you download the notebook as html, the bitmaps for the spectrograms are missing. With png, all is fine.

**Comment by dsblank** [comment]
Ok, thanks for that. That should help in identifying the issues.
