### ISSUE TITLE
About the output of printf.

### ISSUE THREAD

**Issue by xfliu** [Calysto/octave_kernel#124]
In the latest version 0.28.3, I found the following problem about printf.

`print("1");`
`print("2");`

The correct output is expected to be:
>12 

But the output is as follows.
>1
>2
>12

On the other hand, the following code gives correct result.
`print("1\n");`
`print("2\n");`
>1
>2

P.S.
Many thanks for your efforts in developing of Octave kernel. 
It is used in our lecture at Niigata University. The above bug is found by my student.
http://www.ces-alpha.org (I created a logo for octave_kernel along with a link to github.)

**Comment by blink1073** [comment]
Thanks for the report, @xfliu!  We would expect the output to match what you'd get from octave-cli, which is:

```python
>> printf('1')
1>> printf('2')
2>> 
```
In our case, it should print:

```
1
2
```

The last part is the result of duplicate printing, which is covered by #129.  Cheers!
