### ISSUE TITLE
Magic Command %parallel

### ISSUE THREAD

**Issue by GrigoriiM** [Calysto/octave_kernel#126]
Hi all,
I have installed Jupyter Octave Kernel. I would like to know does magic command %parallel operate correctly? If it does, how can I fix the following error:
![error_3](https://user-images.githubusercontent.com/39166245/40052749-692915f6-5847-11e8-8d0c-53d1242b7d4f.png)

I have the same error on two configurations: Windows 7, Octave 4.0.3, Python 2.7.14, ipyparallel 6.1.1 or Ubuntu 16.04, Octave 4.2.1, Python 2.7.12, ipyparallel 6.1.1.

**Comment by dsblank** [comment]
Apparently, the octave_kernel top-level Python package doesn't import OctaveKernel automatically, so you must:

```
%parallel octave_kernel.kernel OctaveKernel
```

**Comment by dsblank** [comment]
Also a note: octave_kernel is not a useful kernel to run in parallel because it doesn't actually return values (nothing in the Out area). It merely prints the answer, like "ans = ANSWER". If we changed it to actually return the answer, then running in parallel would make sense.

**Comment by dsblank** [comment]
(Also made a fix that will be released in the next Metakernel version that allows parallel to work with octave, even if it doesn't return anything)
