### ISSUE TITLE
Sample notebook doesn't work the same as shown

### ISSUE THREAD

**Issue by louy2** [Calysto/octave_kernel#127]
Versions:
macOS 10.13.4
octave_kernel 0.28.2
octave 4.3.0+
gnuplot 5.2.3
Anaconda Python 3.6.4
Jupyter Notebook 5.5.0

Problems:
1. svg plot is huge
2. png plot doesn't show
3. imshow for image too small to display raw doesn't show
4. add title doesn't show
5. another png plot doesn't show

[octave_kernel.ipynb.zip](https://github.com/Calysto/octave_kernel/files/2015422/octave_kernel.ipynb.zip)

**Comment by dsblank** [comment]
It would be best to break these into separate issues, and for each one provide more details/explanation. For example:

1. Did you try using the sizing options for %figure?
2. Do you see any errors in the console?
3. Can you list small example code in the issue tracker, rather than requiring one to download/run a notebook?

**Comment by louy2** [comment]
1. No, the sizing options only changed the viewport size, not the image beneath. Options basically just disabled scrolling.
2. It's been quite some time but I don't remember seeing any particularly helpful errors. After all the image was successfully made, just wrong dimensions.
3. The source code was just the example notebook ([/octave_kernel.ipynb in master branch](https://github.com/Calysto/octave_kernel/blob/master/octave_kernel.ipynb)) unmodified. I included the notebook file to show the artifacts from my running it, thinking it to be the most comprehensive way to show such artifacts. I probably should have also included screenshots, but they weren't much more helpful than my descriptions and probably wouldn't lead you to reproduce it anyway.
