### ISSUE TITLE
print error in kernel

### ISSUE THREAD

**Issue by thalesmaoa** [Calysto/octave_kernel#128]
Hi, I have no problem ploting and saving a figure within octave, however when I try the plot command inside jupyter It gets an error:

```
Inline plot failed, consider trying another graphics toolkit
error: __osmesa_print__: Depth and stencil doesn't match, are you sure you are using OSMesa >= 9.0?
error: called from
    _make_figures>safe_print at line 126 column 7
    _make_figures at line 45 column 13
``` 

I don't use gnuplot and everything is ok when I try print command inside octave.
I tried editing _make_figures.m but I have no idea when it is called inside that function I get an error.

**Comment by dsblank** [comment]
Looks like it could be an octave issue. Googling the "Depth and stencil doesn't match, are you sure you are using OSMesa" error gives:

```
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877149
http://octave.1599824.n4.nabble.com/OSMesa-gt-9-0-td4673739.html
```

The first suggests:

```
export LD_PRELOAD=libGLX_mesa.so.0
```
before starting jupyter. You might try that, os something else on those pages.

**Comment by thalesmaoa** [comment]
I've saw these references, however that's not my problem, I think.

I tried to manually debug and found that print command works great with octave but fails when called from jupyter. Maybe a variable set. I really don't know.

I couldn't evolve because I have no clue how to clever debug inside the notebook.

**Comment by thalesmaoa** [comment]
Just an update! Just tried to reproduce this error in octave-cli and I couldn't! Is there any special argument that metakernel use to call octave? I really need plot problem working.

**Comment by dsblank** [comment]
I don't believe that there are any special arguments. Did you try:

```bash
export OCTAVE_EXECUTABLE=octave-cli
```

**Comment by dsblank** [comment]
Thanks for the update! If you would like to send an Pull Request for updating the README with your hint, that would be great.
