### ISSUE TITLE
plot output not shown in notebook inline [0.12.4]

### ISSUE THREAD

**Issue by maartenscholl** [Calysto/octave_kernel#13]
After installing the kernel using

    pip install git+https://github.com/Calysto/octave_kernel

I can create an Octave notebook that does computations and supllies me with outputs.

However, doing a simple plot gives empty output 

    plot([0, 1], [1 1])

There is a single warning in the console:

     [W 19:39:42.564 NotebookApp] 404 GET     
     /static/components/codemirror/mode/octave_kernel/octave_kernel.js?v=20150902193847     
     (62.195.147.247) 10.30ms referer=https://****************/notebooks/Untitled1.ipynb?     
     kernel_name=octave_kernelgnuplot 4.2 patchlevel 6

Inspecting the HTML I see that it doesn't create any HTML element for the result/plot... 

    <div class="output_area"><div class="prompt output_prompt">Out[3]:</div></div>

... whereas it succeeds in creating output for computations, for example 1 + 2 gives:

    <div class="output_subarea output_text output_result"><pre>ans =  3</pre></div>

I have tried this on both Ipython 3.2.1 and Ipython 4.0.0

**Comment by maartenscholl** [comment]
Also in .octave_hist ( I use Octave 3.4.3) I can see that octave is being called and that the plots are created in /tmp (.png files)

**Comment by blink1073** [comment]
Hmm, I honestly am not sure why that would happen.  You checked that the png files are valid images?

**Comment by maartenscholl** [comment]
the png files turned out to be empty, I replicated the steps by doing them in octave directly and found that xfig was not installed on the server. installing epstool, pstoedit, transfig resolved the issue

**Comment by blink1073** [comment]
Great, I'm glad you got it sorted, cheers.
