### ISSUE TITLE
set"OCTAVE_EXECUTABLE" environment variable

### ISSUE THREAD

**Issue by TerenceLiu98** [Calysto/octave_kernel#133]
I rewrite my raspi sd card and want to install Octave_kernel. But when I start a new .Ipynb, it shows: `Octave Executable not found, please add to path or set"OCTAVE_EXECUTABLE" environment variable`

My device is raspberry pi 3b; system is raspbian

**Comment by TerenceLiu98** [comment]
@dsblank I type `which octave` It has no response : 

``` 
pi@raspberrypi:~ $ which octave
pi@raspberrypi:~ $ 
```

**Comment by dsblank** [comment]
Then you need to install octave.

**Comment by TerenceLiu98** [comment]
Thanks, the problem solved
