### ISSUE TITLE
All plots with black background

### ISSUE THREAD

**Issue by AtheistApe** [Calysto/octave_kernel#134]
The octave kernel appears functional BUT every plot appears with a black background. For example,

```
x = randn(100,1);
y = randn(100,1);

scatter(x, y);
```

produces:

![image](https://user-images.githubusercontent.com/21245221/42480679-85f9166e-8393-11e8-9aa4-575c59f6abb1.png)

**Comment by blink1073** [comment]
Hi @AtheistApe, this is a known issue with Octave, can you please try with `%plot -f png` at the start of the cell?

**Comment by AtheistApe** [comment]
Hi @blink1073, Thanks for replying. I tried you suggestion but it produces no change in the output.

**Comment by blink1073** [comment]
Hmm, how about with `%plot -f svg`?

**Comment by AtheistApe** [comment]
Hey, that worked!

Will I always need to have that line in any plot that I make or is there a way around that?
