### ISSUE TITLE
"imagesc" command woes

### ISSUE THREAD

**Issue by AtheistApe** [Calysto/octave_kernel#135]
I previously had a problem with graphics commands in Jupyter lab / Jupyter notebook (notably, "hist" and "plot") which produced plots with black backgrounds. This was "fixed" by initializing the notebook with "%plot -f svg".

I've recently noticed that the "imagesc" command produces no plot in Jupyter lab with "%plot -f svg" in effect. However, it does produce a plot in **Jupyter notebook** (see below).

The matrix "A" is a 5 x 5 magic square: A = magic(5);

The plot in **Jupyter notebook** with "%plot -f svg" in effect:
![imagesc](https://user-images.githubusercontent.com/21245221/43039937-9d4e598e-8cec-11e8-82f1-a48dfb79de6d.png)

but the gray colormap doesn't seem to work (see below):
![imagesc_gray](https://user-images.githubusercontent.com/21245221/43039965-479d00f2-8ced-11e8-9335-7e237ad2a034.png)

I can get the "imagesc" command to work in **Jupyter lab** by initializing the cell with "%plot -f png" (see below):
![imagesc_lab](https://user-images.githubusercontent.com/21245221/43039984-b45e9cb4-8ced-11e8-8c8c-0410c2407644.png)

and the gray colormap works as expected (see below):
![imagesc_lab_gray](https://user-images.githubusercontent.com/21245221/43039997-e7723ee4-8ced-11e8-887b-9ea6b3608b56.png)

Notice the difference in quality between the colormaps in Jupyter lab and Jupyter notebook; The one in Jupyter notebook is more refined.

**Comment by blink1073** [comment]
Hi @AtheistApe, I agree plotting is more awkward than it needs to be.  I plan to take the guessing out of it and make the choice of `imwrite` vs `print` explicit, but it will require a solid chunk of time that I don't have in the short term.
