### ISSUE TITLE
octave 4.4.0 on Jupyter Notebook for windows 10 dies

### ISSUE THREAD

**Issue by mmarikar** [Calysto/octave_kernel#136]
On bringing up octave 4.4.0 for anaconda 3 Jupyter Notebook on windows 10 the 1st octave-gui.exe system error is: The code execution cannot proceed because liboctave-5.dll was not found. Reinstalling the program may fix this problem. 
Octave 4.4.0 runs in the gui by itself but not with jupyter Notebook. 
Using Python 3.6.5 which runs in Jupyter Notebook. I was able to run Octave 4.0.1 in Jupyter Notebook.

**Comment by mmarikar** [comment]
Install was done using conda and not pip

**Comment by blink1073** [comment]
Hi @mmarikar, do you have an `octave-cli.exe`, and does it run without the dll error from the terminal?

**Comment by mmarikar** [comment]
Yes. You are correct. Octave runs in Jupyter Notebook if OCTAVE_EXECUTABLE
is made equal to octave_cli.exe

**Comment by mmarikar** [comment]
Hi Sylvester,The octave 4.4.0 model worked in Jupyter Notebook but the
graphs produced for (3,3,9) had the x axis labels overwritten
Is there some magics or other work around?
Thanks,
Mo

The code snippet for the graphs are
%Plots
subplot(3,3,1), plot(time, MB)
if tstop < 48
    xlabel('Hours')
else
    xlabel('Days')
endif
ylabel('Mass balance')
title('Mass Balance')

subplot(3,3,2), plot(time, dose)
if tstop < 48
    xlabel('Hours')
else
    xlabel('Days')
endif
if inhalation
    ylabel('Amount inhaled (mg)')
    title('Amount Inhaled')
elseif oral
    ylabel('Oral dose (mg)')
    title('Oral dose')
elseif iv
    ylabel('IV dose (mg)')
    title('IV dose')
elseif dermal
    ylabel('Dermal dose (mg)')
    title('Dermal dose')
endif
if inhalation && dermal
    ylabel('Dose Inh + Dermal (mg)')
    title('Dose Inhalation + Dermal')
endif

subplot (3,3,3),plot(time, CV)
if tstop < 48
    xlabel('Hours')
else
    xlabel('Days')
endif
ylabel('Venous blood (mg/L)')
title('Conc. Venous Blood')

subplot(3,3,4), plot(time, CPP )
if tstop < 48
    xlabel('Hours')
else
    xlabel('Days')
endif
ylabel('Poorly  perfused (mg/L)')
title('Conc. Poorly Perfused')

if oral
    subplot(3,3,5), plot(time, Amount_lumen)
    if tstop < 48
        xlabel('Hours')
    else
        xlabel('Days')
    endif
    ylabel('Amount GI lumen (mg)')
    title('Amount in GI lumen')
else
    subplot(3,3,5),plot(time, CGI)
    if tstop < 48
        xlabel('Hours')
    else
        xlabel('Days')
    endif
    ylabel('Conc. GI tissue (mg/L)')
    title('Conc. GI Tissue')
endif

subplot(3,3,6), plot(time, A_met)
if tstop < 48
    xlabel('Hours')
else
    xlabel('Days')
endif
ylabel('Amount metabolized(mg)')
title('Amount metabolized')

subplot(3,3,7), plot(time, CL)
if tstop < 48
    xlabel('Hours')
else
    xlabel('Days')
endif
ylabel('Conc. liver (mg/L)')
title('Conc. liver')

subplot(3,3,8), plot(time, CF)
if tstop < 48
    xlabel('Hours')
else
    xlabel('Days')
endif
ylabel('Conc. fat (mg/L)')
title('Conc. Fat')

subplot(3,3,9), plot(time, CSK)
if tstop < 48
    xlabel('Hours')
else
    xlabel('Days')
endif
ylabel('Conc. skin (mg/L)')
title('Conc. Skin')

disp(['Mass balance = ' num2str(MB(end))])
disp(['Elapsed time in seconds = ' num2str(etime(clock,start_time))])
disp('Done')
beep

The actual graphs for Octave proper show the labels cleanly as indicated
immediately below:



The graphs for Jupyter Notebook however have the x axis labels overwritten
as indicate dbelow

**Comment by dsblank** [comment]
Can you give a minimal example of the problem? Also, to attach pictures you'll have to use the github interface I think.

**Comment by mmarikar** [comment]
Attached is a nonsensical example of 3,3,9 that demonstrates what I got in
the model I was working on.
2,2,4 for example does not have the titles being overwritten.

**Comment by dsblank** [comment]
As far as I know, you cannot attach items via the github email interface.

**Comment by dsblank** [comment]
Looks like the subaxis command can take additional parameters, like:

```
subaxis(4,6,1, 'Spacing', X, 'Padding', X, 'Margin', X, 'SpacingVert', X);
```

**Comment by mmarikar** [comment]
Sorry Doug, but subaxis is not implemented in octave. Its a matlab centric
command.
The easiest way to see what I mean by the graphs being crunched in Jupyter
Octave is to try the demo example for octave where it works beautifully. In
jupyter Notebook for octave the labels get crunched.
Unless someone can demo an example for me this is a definite bug.
Please enter it as such.

**Comment by blink1073** [comment]
@mmarikar, we are fundamentally limited by the `print` command in Octave, since we rely on it to produce the images used by the kernel.  The output of the `print` command varies in quality (and content!) by plot backend and image type.
