### ISSUE TITLE
getting octave kernel working in Jupyter notebook in osx mavericks

### ISSUE THREAD

**Issue by jaydautcher** [Calysto/octave_kernel#14]
Do you have advice on how I can get an octave kernel working in a Jupyter notebook in OSX mavericks?

##### Background:  
Up to now I've been running ipython notebooks using in python 2.7. I'm starting to work in Octave, and would like to run a Jupyter notebook using the Octave kernel. Using conda I created a new environment to run Python 3.5, and pip installed the octave_kernel and some other packages (a complete pip list output is shown below). From within that new environment, entering 'ipython notebook' or 'jupyter notebook' at terminal prompt lets me open a notebook in the browser, but the only kernel available using the 'kernel' tab is python3.  I've added a few observations in case they contain relevant info. Any help would be appreciated.

##### observation 1
from within ipython console, the command  
```python
 import imp; print(imp.find_module('octave_kernel')[1])
```
returns
```python
   //anaconda/envs/snakes/lib/python3.5/site-packages/octave_kernel.py
```
##### observation 2
from terminal the command
```bash
	ipython qtconsole --kernel=octave_kernel
```
returns
```bash
	[JupyterQtConsoleApp] CRITICAL | Could not find kernel octave_kernel
```
##### observation 3
To run octave_kernel in a jupyter notebook do I need to have the octave app installed at all (just not clear on this), and if I do, does the octave pathname need to be findable by the jupyter notebook in some way? I had Octave installed, thought maybe my problems running octave kernel were related to my octave pathname, so from within my new 3.5 environment I reinstalled Octave using 'brew cask install octave' thinking that might fix a pathname issue but observations 1 and 2 above still hold.

##### observation 4
on a different isse thread you asked ivy-xiao if her kernels were in /usr/local/share/jupyter/kernels/ or ~/.ipython/kernels. I'm not clear; your octave_kernel.py file, does a copy of that file need to be in one of those locations, and does that pathname need to be recorded somewhere?

##### pip list
appnope (0.1.0)
decorator (4.0.2)
gnureadline (6.3.3)
ipykernel (4.0.3)
ipython (4.0.0)
ipython-genutils (0.1.0)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter-client (4.0.0)
jupyter-core (4.0.6)
MarkupSafe (0.23)
metakernel (0.10.6)
mistune (0.7.1)
nbconvert (4.0.0)
nbformat (4.0.0)
notebook (4.0.4)
octave-kernel (0.12.4)
path.py (8.1.1)
pexpect (3.3)
pickleshare (0.5)
pip (7.1.2)
ptyprocess (0.5)
Pygments (2.0.2)
pyzmq (14.7.0)
qtconsole (4.0.1)
setuptools (18.1)
simplegeneric (0.8.1)
terminado (0.5)
tornado (4.2.1)
traitlets (4.0.0)
wheel (0.24.0)

**Comment by blink1073** [comment]
The python file is used to run the kernel, but the kernel spec file is what registers the kernel with Jupyter.  What is the output of `ls /usr/local/share/jupyter/kernels/`?

**Comment by jaydautcher** [comment]
thanks for the reply!

$ ls /usr/local/share/jupyter/kernels

ls: /usr/local/share/jupyter/kernels: No such file or directory

$ ls /usr/local/share/jupyter

ls: /usr/local/share/jupyter: No such file or directory

I went back just now, to make sure I was fully updated to jupyter, and
typed

conda update jupyter

and it said I was all already up to date.

Jay

**Comment by blink1073** [comment]
How about `ipython kernelspec list`?

**Comment by blink1073** [comment]
You might also try `pip install -U octave_kernel`, I just released a new version.

**Comment by jaydautcher** [comment]
Thanks!  ```pip install -U octave_kernel``` worked. 
Now ```ls /usr/local/share/jupyter/kernels/``` returns ```octave_kernel```; and ```ipython kernelspec list``` returns both ```octave_kernel``` and ```python3```

**Comment by blink1073** [comment]
Great, cheers!
