### ISSUE TITLE
Cannot use plot() at all. 

### ISSUE THREAD

**Issue by rr1610** [Calysto/octave_kernel#143]
My issues comes in 2 parts: 

a) Running `available_graphics_toolkits` within jupyter gives just `fltk`. But doing so within GNU Octave regular gui gives both `fltk` and `qt`. Is this a problem, or should it be expected?

b) The bigger issue though is that Octave within Jupyter fails to use plot. After defining a standard sine function and attmepting to plot with `plot (x,y)`. I recieve the following error:
   ```
 error: feval: /usr/lib/octave/4.4.1/oct/x86_64-pc-linux-gnu/__init_fltk__.oct: failed to load:     libfltk_gl.so.1.3: cannot open shared object file: No such file or directory
error: called from
    graphics_toolkit at line 91 column 5
    figure at line 89 column 7
    newplot at line 117 column 10
    plot at line 222 column 9

Inline plot failed, consider trying another graphics toolkit
error: print: no axes object in figure to print
error: called from
    _make_figures>safe_print at line 122 column 7
    _make_figures at line 44 column 13

```

My first thought was that my user didnt have access to the `.../__init_fltk__.oct` file, but from what I can tell that isn't the case. Im a complete beginner with Octave, so granted I haven't tested much, but `plot()` is the only aspect that isnt working. Anyone come across this bug/problem before and can help?

I installed octave_kernel using ` conda install -c conda-forge octave_kernel `. Am running the most up-to-date versions of both Jupyter Notebook and Octave. Installed on Manjaro.

**Comment by rr1610** [comment]
I realised that I didnt have `gnuplot` installed on this system. Just having done so and using `graphics_toolkits("gnuplot")` allows `plot()` to work fine. But still curious to why there was a problem beforehand, and why there still is a problem is I dont explictly choose `gnuplot`?

**Comment by blink1073** [comment]
The gnuplot event loop is the only one that plays nicely with our pty connection.

**Comment by TheodoreEhrenborg** [comment]
> I realised that I didnt have `gnuplot` installed on this system. Just having done so and using `graphics_toolkits("gnuplot")` allows `plot()` to work fine. 

Thanks! Running this before I called `plot` worked for me too. Small clarification: It's spelled `graphics_toolkit("gnuplot")`
