### ISSUE TITLE
Waitbar suggestion

### ISSUE THREAD

**Issue by thalesmaoa** [Calysto/octave_kernel#144]
I have a loop inside my notebook which takes a while. From 30 to 60min. In octave I use waitbar command. Any suggestion on how to implement any visual progress bar inside Jupyter?

**Comment by blink1073** [comment]
You can sprintf a line that starts with `\r` and an increasing number of hyphens as an approximation of a status bar.

**Comment by thalesmaoa** [comment]
```
for i = 1:50
    sprintf("\r");
    fprintf("%d",i);
end
```
```
1234567891011121314151617181920212223242526272829303132333435363738394041424344454647484950
1234567891011121314151617181920212223242526272829303132333435363738394041424344454647484950
```
Is there a way to avoid printing twice?

**Comment by blink1073** [comment]
```
for i = 1:50
    pause(0.1)
    fprintf("\r%d",i);
end
```

**Comment by thalesmaoa** [comment]
I can't get it to work here. It only display the result after the for ends.

![image](https://user-images.githubusercontent.com/14074573/51703708-36059300-1ffe-11e9-994b-fa6415e10dda.png)

**Comment by blink1073** [comment]
This now works if you run `pip install -U metakernel`:

```matlab
for i = 1:50
    pause(0.1)
    fprintf("\r%d",i);
end
```

**Comment by ha7ilm** [comment]
Now this also works for me, after correctly upgrading the packages with `pip3` (the same problem that I had in #149).

**Comment by ha7ilm** [comment]
I created the following one-liner to display a waitbar:

    cwaitbar=@(val,maxval) printf(["\r" repmat("█",1,round(50*val/maxval)) repmat("░",1,round(50*(1-val/maxval))) " %d/%d"],val,maxval);

![image](https://user-images.githubusercontent.com/5903408/57125239-f7177400-6d88-11e9-816c-2b1d53c4a460.png)

As a note, it only shows up during progress if at least a line ending with `\n` is printed before it. 

```matlab
printf("\n") %nothing with show up without this
for i=1:10
    pause(0.5)
    cwaitbar(i,10)
end
```
