### ISSUE TITLE
computer freezes when it gets out of memory

### ISSUE THREAD

**Issue by leolca** [Calysto/octave_kernel#145]

**Comment by leolca** [comment]
By mistake I create a row audio vector (1 x 26461) and another as a column (26461 x 1). When taking the difference Octaves performs operator broadcast and intends to create a large matrix (26461 x 26461), running out of memory. When running through the Octave_kernel for Jupyter it freezes everything.

**Comment by blink1073** [comment]
Hi @leolca, there isn't anything for us to do on this one, we're just passing through the command to Octave.
