### ISSUE TITLE
Fixed: plot command fails MacOS Mojave with Octave 5.1.0

### ISSUE THREAD

**Issue by jrminter** [Calysto/octave_kernel#147]
First, thanks for releasing and offering assistance. Thought I'd pass on a fix...
You might want to add it to the README.md file...

I have the Octave kernel working on my MacBook Pro on Mojave after setting an enviroment variable to my Octave executable. I am testing the octaveBasic.ipynb file.

The problem is I am using gnuplot with a qt terminal, not aqua.

The error:

```
gnuplot> set terminal aqua enhanced title "Figure 1" size 560 420  font "*,6.66667" dashlength 1
                      ^
         line 0: unknown or ambiguous terminal type; type just 'set terminal' for a list

WARNING: Plotting with an 'unknown' terminal.
No output will be generated. Please select a terminal with 'set terminal'.
```

The solution:

I added 

```
setenv("GNUTERM","qt");
```

to `.octaverc`

**Comment by blink1073** [comment]
Thanks for the report, @jrminter!  Fixed in master.
