### ISSUE TITLE
Failed to connect to kernel 

### ISSUE THREAD

**Issue by lux12337** [Calysto/octave_kernel#150]
Hi, after i run the commands:
`conda config --add channels conda-forge`
`conda install octave_kernel`
I open up JupyterHub and try to run an Octave notebook but it gets stuck loading the kernel and eventually fails to connect. Thanks for the help!
![image](https://user-images.githubusercontent.com/19236515/56945301-99aacb00-6adb-11e9-818e-f21e0c8c5bb5.png)

**Comment by blink1073** [comment]
Hi @lux12337!  A few things to try from a command line (can you please paste the output).

```
which octave
echo $OCTAVE_EXECUTABLE
ls $OCTAVE_EXECUTABLE
python -c "from octave_kernel.kernel import OctaveEngine; print(OctaveEngine().eval('ones(3)'))" 
```

**Comment by lux12337** [comment]
Hi @blink1073 , this is what i get:
![image](https://user-images.githubusercontent.com/19236515/56987856-6b60d600-6b43-11e9-93b8-77764d3514a3.png)

**Comment by blink1073** [comment]
A few more items:

```bash
which conda
which python
which Jupyter
```

My guess is those are different root paths.

**Comment by lux12337** [comment]
Here is the output that i get, I'm running 'The littlest JupyterHub' on a VirtualBox for reference:
![image](https://user-images.githubusercontent.com/19236515/56994609-6ce6ca00-6b54-11e9-8707-845e6a4a632f.png)

**Comment by blink1073** [comment]
Those are different prompts between the two screenshots, I think you might have something else on your PATH in the terminal session with the green text.

**Comment by lux12337** [comment]
Hi @blink1073 , I apologize if my last replies were not detailed enough for you to get a clearer picture of my problem. I was able to figure out the problem myself. I had installed the Octave kernel with conda but completely forgot to install octave in the first place. I used `sudo conda install octave` to fix the problem. Thank you for all the help!

**Comment by blink1073** [comment]
Glad you got sorted, cheers!
