### ISSUE TITLE
ErrorI: nvalid response: 403 Forbidden

### ISSUE THREAD

**Issue by Foadsf** [Calysto/octave_kernel#155]
I installed the kernel using `pip install octave_kernel` but I get the error:

> ErrorI: nvalid response: 403 Forbidden

![octave1](https://user-images.githubusercontent.com/12762442/57618266-3a40c680-7583-11e9-8d2e-5bc3dcc18da1.PNG)

and then:

> Launcher Error e is undefined

![octave2](https://user-images.githubusercontent.com/12762442/57618309-547aa480-7583-11e9-9ea0-496aa9890665.PNG)

My OS is Windows 10 build 1809
Python version 3.7.3
Octave version 5.1.0
Jupyter lab version 0.35.6

**Comment by blink1073** [comment]
Hi @Foadsf, does this also happen when launching a Python kernel?  

Also, can you please include the browser console log?

**Comment by Foadsf** [comment]
@blink1073 apologies for the late reply. Wish there were a GitHub Android app to get these notifications faster. Do you have Twitter?

No Python is fine. How can I get the browser console log?

**Comment by blink1073** [comment]
I don't use social media, it isn't good for my mental health.  :smile:

Did you run JupyterLab from the root `C:` by chance?

The browser log can be found by hitting F12 and selecting the Console tab in the developer tools (on either FF, Chrome, or Edge).

**Comment by Foadsf** [comment]
@blink1073 

> I don't use social media, it isn't good for my mental health. 😄

You are doing the right thing :))

running the Jupyter notebook from an arbitrary path I get this error:

> Connection failed A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

> ![Jup](https://user-images.githubusercontent.com/12762442/58416359-99bdcc80-8081-11e9-9b2f-a357c94250bd.PNG)

and this is the log information I get in the console:

> Firefox can’t establish a connection to the server at ws://localhost:8888/api/kernels/b2a125be-4178-40b2-a890-4acacee617f0/channels?session_id=a21a93466836420baaf5fc5b78df01b9. kernel.js:461
Kernel: kernel_disconnected (b2a125be-4178-40b2-a890-4acacee617f0) kernel.js:103
WebSocket connection failed:  ws://localhost:8888/api/kernels/b2a125be-4178-40b2-a890-4acacee617f0 true kernel.js:544
Connection lost, reconnecting in 64 seconds.

**Comment by blink1073** [comment]
It looks like websockets are disabled, either in FF itself or with something like an antivirus program.  You can rule out FF by trying in Edge or Chrome.

**Comment by Foadsf** [comment]
OK, this seems to be a simple issue. The `octave.exe` was not detected by the OS. As I have described [here](https://superuser.com/a/1448048/588662), I added the path to the `octave.exe` to the environment variables and it works like a charm now!

**Comment by blink1073** [comment]
Great!
