### ISSUE TITLE
Tests fail with Octave 5

### ISSUE THREAD

**Issue by QuLogic** [Calysto/octave_kernel#159]
An [auto-rebuild](https://apps.fedoraproject.org/koschei/build/6585992) with Octave 5 is now failing:
```
======================================================================
FAIL: test_completion (__main__.OctaveKernelTests) (text='one')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/jupyter_kernel_test/__init__.py", line 135, in test_completion
    set(sample['matches']))
AssertionError: Items in the second set but not the first:
'onenormest'
----------------------------------------------------------------------
```
In Octave 5, `onenormest` was [removed](https://www.gnu.org/software/octave/NEWS-5.1.html#removed-functions-and-properties).

**Comment by blink1073** [comment]
Thanks for the report!  Do you know of a suitable replacement that has more than one completion and is available in both 4 and 5?  cf https://github.com/Calysto/octave_kernel/blob/6f86ad7f25a7a84ea7530618b5ae8d292301317b/test_octave_kernel.py#L21

**Comment by QuLogic** [comment]
How about `acos`?
```
octave:1> acos
acos   acosd  acosh  
```

**Comment by blink1073** [comment]
Sounds good. I'm afk until Sunday, would you like to make a PR?
