### ISSUE TITLE
Variable exchange with magic %python

### ISSUE THREAD

**Issue by thalesmaoa** [Calysto/octave_kernel#161]
I'm running octave as the main language to control Finite Elements software. I'm also using python to update a drawing since the CAD (FreeCAD) is only compatible with python.

I just need to create a variable:

`A = 1`

```
%%pyton -input A
print(A)
```

I don't know how to get it working...

**Comment by blink1073** [comment]
Hi @thalesmaoa, unfortunately metakernel (and octave kernel by extension) does not support passing variables to the `%%python` magic.

**Comment by thalesmaoa** [comment]
I've found a package that can probably help with that.

https://gitlab.com/mtmiller/octave-pythonic

I will give it a try and report latter.
