### ISSUE TITLE
Octave kernel not showing as option in JupyterHub / Jupyter Notebook.

### ISSUE THREAD

**Issue by vroomanj** [Calysto/octave_kernel#162]
I am running JupyterHub with a Docker Swarm back-end. I have a Notebook image built and have installed Octave. Octave launches properly in the terminal of my Notebook.

I installed octave_kernel using the following:
> conda install -c conda-forge octave_kernel texinfo

I set OCTAVE_EXECUTABLE as follows:
> OCTAVE_EXECUTABLE '/usr/bin/octave-cli'

I have corrected the Octave kernel.json using the following:
> sed -ir 's/"argv": \["python",/"argv": \["\/opt\/anaconda3\/bin\/python3",/g' /opt/anaconda3/share/jupyter/kernels/octave/kernel.json

The kernel shows up in the kernel list:
> $ jupyter kernelspec list
> Available kernels:
>   bash       /opt/anaconda3/share/jupyter/kernels/bash
>   octave     /opt/anaconda3/share/jupyter/kernels/octave
>   python2    /opt/anaconda3/share/jupyter/kernels/python2
>   python3    /opt/anaconda3/share/jupyter/kernels/python3
>   vpython    /opt/anaconda3/share/jupyter/kernels/vpython

And the kernel.json contains the following:
> $ cat /opt/anaconda3/share/jupyter/kernels/octave/kernel.json
> {
>     "argv": ["/opt/anaconda3/bin/python3",
>              "-m", "octave_kernel",
>              "-f", "{connection_file}"],
>     "display_name": "Octave",
>     "mimetype": "text/x-octave",
>     "language": "octave",
>     "name": "octave"
> }

I have my KernelSpecManager.whitelist set as follows:
> echo "c.KernelSpecManager.whitelist = {'bash','octave','python2','python3'}" >> /opt/anaconda3/etc/jupyter/jupyter_notebook_config.py

However, despite all of this, the Octave kernel is not an option in the drop-down menu of kernels. Can anyone offer assistance? What additional information can I provide that might help you with diagnosing/helping with my problem (if anything)?

**Comment by blink1073** [comment]
Is the bash kernel shown but not the Octave kernel?  Can you pass args to the spawner to run with the `--debug` flag set and see if there is anything of interest in the log when the user's server starts?

**Comment by vroomanj** [comment]
@blink1073: The bash, python2 and python3 kernels are shown but not the Octave kernel. I will try using the --debug flag tonight when I am able to take the Hub down temporarily.

**Comment by blink1073** [comment]
:+1:

**Comment by vroomanj** [comment]
Closing issue. This was my fault. My c.KernelSpecManager.whitelist in my user .jupyter/jupyter_notebook_config.py was overriding the system's whitelist and octave wasn't in the whitelist.
