### ISSUE TITLE
Add a guide

### ISSUE THREAD

**Issue by Bonsanto** [Calysto/octave_kernel#17]
I really suggest to add a guide, I don't understand how to install this kernel and the README.md doesn't help at all

**Comment by blink1073** [comment]
Hi @Bonsanto, I updated the README, is that any clearer?  https://github.com/Calysto/octave_kernel/blob/master/README.rst

**Comment by dsblank** [comment]
Looks good! Of course, we can always use more docs, and PRs always encouraged :)
