### ISSUE TITLE
magics

### ISSUE THREAD

**Issue by 59hqtRu1** [Calysto/octave_kernel#171]
This probably isn't an issue, just something I haven't understood.

It says on the github site that magics are available in the Octave kernel, but when I try, say, %lsmagic in a jupyter notebook cell, nothing happens, which isn't really surprising because % indicates a comment in Octave.  So how do I get the magics with the Octave kernel?

Thanks

**Comment by dsblank** [comment]
Not all ipython magics area avilable, but I believe that these should work (even though % is a comment):

https://github.com/Calysto/metakernel/blob/master/metakernel/magics/README.md

**Comment by dsblank** [comment]
The metakernel magics must appear at top, on very left of line.

**Comment by 59hqtRu1** [comment]
Ahh, yes, that makes them work.  Thanks!

**Comment by dsblank** [comment]
Great! Thanks for confirming!
