### ISSUE TITLE
Unstable Octave running in Jupyter Notebook

### ISSUE THREAD

**Issue by alanbazzaz** [Calysto/octave_kernel#176]
Octave stops, gives wrong results and errors. Please help. I'm new to using Octave, and installing software through command line.
I suspect the issue with the way I installed everything, but please let me know how to correct. Below are some of the environment variables.
I'm running OS X 10.15.4

Alan-New-Air-2:~ alan$ which octave
/usr/local/octave/3.8.0/bin/octave
Alan-New-Air-2:~ alan$ echo $OCTAVE_EXECUTABLE

Alan-New-Air-2:~ alan$ ls $OCTAVE_EXECUTABLE
Applications				Untitled7.ipynb
Desktop					Untitled8.ipynb
Documents				Untitled9.ipynb
Downloads				anaconda3
Dropbox					anaconda_ete
Google Drive				dwhelper
Google Drive (bazzazwasfi@gmail.com)	get-pip.py
Google Drive (lorotary@gmail.com)	oswegan_db.xlsx
Library					rent_roll_out.csv
MacKeeper Backups			rent_roll_out.xlsx
Movies					rent_table.csv
Music					resident_table.csv
My Cloud				saved page.htm
Pictures				setuptools-26.1.1-py2.py3-none-any.whl
Public					six-1.10.0-py2.py3-none-any.whl
Resident Table.xlsx			soup_tree
Sites					soup_tree.txt
Station Square.xlsx			src
Untitled.ipynb				table example.html
Untitled1.ipynb				table example.odt
Untitled10.ipynb			test html table.py
Untitled11.ipynb			test.php
Untitled2.ipynb				unit_table.csv
Untitled3.ipynb				web testing.py
Untitled4.ipynb				webencodings-0.5.tar.gz
Untitled5.ipynb				webtest.py
Untitled6.ipynb
Alan-New-Air-2:~ alan$ python -c "from octave_kernel.kernel import OctaveEngine; print(OctaveEngine().eval('ones(3)'))" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named octave_kernel.kernel

Alan-New-Air-2:~ alan$ which conda
/Users/alan/anaconda3/condabin/conda
Alan-New-Air-2:~ alan$ which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
Alan-New-Air-2:~ alan$ which jupyter
Alan-New-Air-2:~ alan$ 

Jupyter is running python 3.6

**Comment by blink1073** [comment]
Hi @alanbazzaz, it looks like you need to activate a conda environment so your `python` executable is the one in that environment.

**Comment by alanbazzaz** [comment]
Thank you, for the enlightening answer.
I’m new to octave and conda. Is there an example you can point me towards?

Much appreciated.
Alan
