### ISSUE TITLE
Multiline cells only output last print command

### ISSUE THREAD

**Issue by luiscruz** [Calysto/octave_kernel#18]
If I put the following in a cell
    printf("Hello world!");
    printf("Hello again!")

My output is:
    Hello again!

I believe this is an issue. It would be really useful if we could get that fixed.

Thanks,
Luis

**Comment by blink1073** [comment]
Hi @luiscruz, I agree it is an issue.  All of the lines are getting run, but not all of the output is getting fed to the front-end (the notebook).  Unfortunately, I am not sure of a solution.

**Comment by luiscruz** [comment]
I am not sure whether I have the skills (or the bandwidth) for this but I will try to take a look at this during the weekend.
Cheers!

**Comment by xfliu** [comment]
Dear blink1073,

In my class, students are using this octave kernel to do matrix computation online. So many thanks for your efforts.

But, the issue discussed here is really a headache for students, because due to this bug, the 
result during the a cell-computation cannot be printed out  for confirmation.

I hope to see some progress in this issue.  Thanks a lot!

LIU

**Comment by dsblank** [comment]
@xfliu I have a special commitment to make any of the Calysto projects work for education. So, I really want to understand the issue.

Until this issue can be addressed, is it a possible work-around to enter one command per cell?

**Comment by xfliu** [comment]
Hi, @dsblank,

My project is running at  http://www.cloud2015.org . For each student, the system provides an independent virtue machine along with a jupyter server running an octave kernel. 

For the moment, for the student and me, we just split the octave codes into several cells to confirm the results.

(The portal page of Cloud2015 is in Japanese but the inner part is in both English and Japanese. If anybody has interest, I can set an account for test. )


Best regards!

**Comment by dsblank** [comment]
@xfliu Thanks for the info! Ok, good to hear that there is a work-around by putting each line in a cell.

I suspect that if this is an issue for Octave, it may affect other kernels as well.

**Comment by blink1073** [comment]
This is fixed by installing the latest metakernel `pip install --upgrade metakernel`.

**Comment by xfliu** [comment]
Dear blink1073, 

Many thanks for your efforts.  But when I confirm the the latest version of metakernel (0.11.5), it seems that the problem still exists.

My test example is as below:
```
x=1
disp(x);
disp(x+10);
```
The output is expected to be:
```
1
11
```
But the result of running the cell of notebook is
```
11
```

Could you help me to confirm this problem again?


By the way, I am using Jupyter 4.0.6 on ubuntu 14.04.

**Comment by blink1073** [comment]
I just tried it with metakernel (0.11.5) again and I get the expected output.  Perhaps you need to restart the kernel?

**Comment by xfliu** [comment]
Octave kernel now works well on my NEW system.

In my system, I am using conda to run both python 2 and python 3 kernels. 
Below is the difference of my system settings.

The OLD setting with problem:
The jupyter under python 2 has been used to start the notebook server. 
In this case, even with the metakernel(0.11.5), the output of octave (with python 3) does not work well.

The NEW setting now working well:
I removed the jupyter under IPython2 and installed the latest jupyter under python3.
Now, octave kernel works well.

**Comment by xfliu** [comment]
I think I should add a  link for the site of "Octave kernel" on my system to show thanks to you and your project.
Do you have any idea?

**Comment by blink1073** [comment]
Hi @xfliu, I'm glad it is working for you now.  I think https://github.com/Calysto/octave_kernel is probably the only real link for the project right now.
