### ISSUE TITLE
Error plotting with Octave 6.1.0 on jupyter notebook

### ISSUE THREAD

**Issue by foxserie** [Calysto/octave_kernel#183]
I have installed two versions of Octave both 32 bits.

- Octave 4.4.1 that was the one I used the most and 
- Octave 6.1.0 that is the most recent one.

*I also have gnuplot 5.2 patch level 7 installed-

The octave kernel is installed in anaconda via:

```conda install octave_kernel```

- to know where to look for the executable in windows you require the enviromental variable, here i tell it to go for Octave-4.4.1:

```OCTAVE_EXECUTABLE ```
```C:\\Octave\\Octave-4.4.1\\bin\\octave-cli.exe```

once it's up and running, the jupyter notebook loads the kernel  and i run the example:

```
x=-10:0.1:10+eps;
y=-10:0.1:10+eps;

[xx,yy]=meshgrid(x,y);

zz= sin(sqrt(xx.^2+yy.^2))./(sqrt(xx.^2+yy.^2));

surf(xx,yy,zz)
view(-35,45)
shading interp
```
[resultant plotting from the code above][1]

If I check the graphic toolkits that display the plots with the commands i get:

```available_graphics_toolkits()```
```
    ans =
    {
      [1,1] = fltk
      [1,2] = gnuplot
    }
```
And the current toolkit is:

```loaded_graphics_toolkits ()```
```
    ans =
    {
      [1,1] = gnuplot
    }
```
 **BUT** if i change the enviromental variable to point to the Octave-6.1.0 executable with: ```C:\\Octave\\Octave-6.1.0\\mingw32\\bin\\octave-cli.exe```

once i run the chunks of code, the ones with calculations are doing fine
```
x=-10:0.1:10+eps;
y=-10:0.1:10+eps;

[xx,yy]=meshgrid(x,y);

zz= sin(sqrt(xx.^2+yy.^2))./(sqrt(xx.^2+yy.^2));
```
for example, if i take the ```;``` off the zz variable you get the matrix printed on the output
```
zz =

 Columns 1 through 6:

   7.0710e-02   7.0912e-02   7.0764e-02   7.0268e-02   6.9428e-02   6.8251e-02
   7.0912e-02   7.0761e-02   7.0254e-02   6.9397e-02   6.8194e-02   6.6655e-02
   7.0764e-02   7.0254e-02   6.9386e-02   6.8166e-02   6.6601e-02   6.4702e-02
   7.0268e-02   6.9397e-02   6.8166e-02   6.6583e-02   6.4658e-02   6.2404e-02
   6.9428e-02   6.8194e-02   6.6601e-02   6.4658e-02   6.2378e-02   5.9773e-02
   6.8251e-02   6.6655e-02   6.4702e-02   6.2404e-02   5.9773e-02   5.6826e-02 ...

 .... etc.
```
but the plot block of code
```
surf(xx,yy,zz)
view(-35,45)
shading interp
```
sends as output the error:
```
Inline plot failed, consider trying another graphics toolkit
error: print: figure must be visible or qt toolkit must be used with __gl_window__ property 'on' or QT_OFFSCREEN feature available
error: called from
    _make_figures>safe_print at line 125 column 7
    _make_figures at line 49 column 13
```
Which tells me  there is somwthing between jupyter kernel  and Octave 6.1.0, maybe Octave handles graphics in a new way?.

I know Octave 6.1.0 is working because the same code produces the correct plot if you run it directly in the octave application gui or cli.

[plot window of the same graph captured from the Octave-gui application][2]

---

The octave kernel says it's working if I check it with the command 

```python -m octave_kernel.check```

The check reveals:

```
Octave kernel v0.32.0
metakernel v0.27.5
Python v3.78.56 <default, Sep  4 2020, 00:03:40> [MSC v.1916 32 bit <intel>]
Python path: C:\Users\myuser\anaconda3\python.exe

Conecting to Octave...
PS C:\Users\myuser> Can't load 'C:\Users\myuser\anaconda3\lib\site-packages\metakernel\magics\shell_magic.py' : error <pexpect.popen_spawn.PopenSpawn object at 0x033C3178>
searcher: searcher_re:
    0: re.compiler<'>'>
<pexpect.popen_spawn.PopenSpawn object at 0x033C3178>
searcher: searcher_re:
    0: re.compiler<'>'>
Octave conection established
Octave kernel v0.32.0 running GNU Octave v6.1.0
Graphics toolkit: fltk
available toolkits: [1,1] = fltk
    [1,2] = gnuplot
>

```
when trying to plot in the jupyter notebook  the console keeps sending a similar error
```
PS C:\Users\myuser> [MetaKernelApp] ERROR : Can't load 'C:\Users\myuser\anaconda3\lib\site-packages\metakernel\magics\shell_magic.py' : error <pexpect.popen_spawn.PopenSpawn object at 0x0341C718>
searcher: searcher_re:
    0: re.compiler<'>'>
<pexpect.popen_spawn.PopenSpawn object at 0x0341C718>
searcher: searcher_re:
    0: re.compiler<'>'>
```

That seems to be also affiliated with accessing  the magic.py file in the metakernel package, when plotting.

  [1]: https://i.stack.imgur.com/1J5TS.png
  [2]: https://i.stack.imgur.com/lCYl7.png

**Comment by larssp** [comment]
Seems like the 'Visible' property is now off by default. Try adding `set(gcf,'Visible','on')` at the end of your plotting cell.

**Comment by lukkesweet** [comment]
I saw this answer over on StackOverflow but you can add the command 

`graphics_toolkit("gnuplot")`

to the beginning of your script to make it work.  Does anyone know how to add this to the kernel?

**Comment by dsblank** [comment]
Looks like that is set in the config settings "backend":

https://github.com/Calysto/octave_kernel/blob/master/octave_kernel/kernel.py#L215

https://github.com/Calysto/octave_kernel#configuration

So:

```
$ cat ~/.jupyter/octave_kernel_config.py
c.OctaveKernel.plot_settings = dict(backend='gnuplot')
```

**Comment by larssp** [comment]
Quite peculiar,  `graphics_toolkit()` returns gnuplot from the start but octave uses fltk for plotting instead.
Unless one additionally invokes  `graphics_toolkit('gnuplot')`. 

See following comparison (Jupyter Lab, WinPython, Win10):

<details>
  <summary>octave 6.2.0</summary>

```octave
version()
```

    ans = 6.2.0
    


```octave
graphics_toolkit()
```

    ans = gnuplot
    


```octave
loaded_graphics_toolkits()
```

    ans =
    {
      [1,1] = gnuplot
    }
    
    


```octave
plot(1:10)
```

    Inline plot failed, consider trying another graphics toolkit
    error: print: figure must be visible or qt toolkit must be used with __gl_window__ property 'on' or QT_OFFSCREEN feature available
    error: called from
        _make_figures>safe_print at line 125 column 7
        _make_figures at line 49 column 13



```octave
fig = figure()
h = plot(1:10);
xlabel('\varphi') % additional indicator: \varphi is not suported in fltk, but it is in gnuplot
set(fig,'Visible','on')
toolkit = get(fig,"__graphics_toolkit__")
```

    fig = 1
    toolkit = fltk
    


    
(plot is shown, xlabel reads verbatim `\varphi` )
    



```octave
graphics_toolkit("gnuplot")
```


```octave
loaded_graphics_toolkits()
```

    ans =
    {
      [1,1] = fltk
      [1,2] = gnuplot
    }
    
    


```octave
fig2 = figure()
h = plot(1:10);
xlabel('\varphi')
toolkit = get(fig2,"__graphics_toolkit__")
```

    fig2 = 1
    toolkit = gnuplot
    


    
(plot is shown, xlabel shows correct symbol)
    


</details>

<details>
  <summary>octave 5.2.0</summary>
  
```octave
version()
```

    ans = 5.2.0
    


```octave
graphics_toolkit()
```

    ans = gnuplot
    


```octave
loaded_graphics_toolkits()
```

    ans =
    {
      [1,1] = gnuplot
    }
    
    


```octave
fig2 = figure()
h = plot(1:10);
xlabel('\varphi')
get(fig2,"__graphics_toolkit__")
```

    fig2 =  1
    ans = gnuplot
    


    
(plot is shown, xlabel shows correct symbol)
    



```octave
graphics_toolkit("fltk")
```


```octave
loaded_graphics_toolkits()
```

    ans =
    {
      [1,1] = fltk
      [1,2] = gnuplot
    }
    
    


```octave
fig = figure()
h = plot(1:10);
xlabel('\varphi') % additional indicator: \varphi is not suported in fltk, but it is in gnuplot
set(fig,'Visible','on')
toolkit = get(fig,"__graphics_toolkit__")
```

    fig =  1
    toolkit = fltk
    


    
(plot is shown, xlabel reads verbatim `\varphi` )
    



```octave
fig = figure()
h = plot(1:10);
xlabel('\varphi') % additional indicator: \varphi is not suported in fltk, but it is in gnuplot
% setting 'Visible' to 'on' omitted
toolkit = get(fig,"__graphics_toolkit__")
```

    fig =  1
    toolkit = fltk
    

    Inline plot failed, consider trying another graphics toolkit
    error: print: figure must be visible or qt toolkit must be used with __gl_window__ property 'on' or QT_OFFSCREEN feature available
    error: called from
        _make_figures>safe_print at line 125 column 7
        _make_figures at line 49 column 13


</details>

Even though [octave bug report 60095](https://savannah.gnu.org/bugs/?func=detailitem&item_id=60095) looks kind of related, this is not reproducible with octave-cli.exe (v6.2.0) nor octave-gui.exe.

**Comment by foxserie** [comment]
Okey I now moved on to Octave 6.3.0 but the problem persists, a solution is as @lukkesweet  has mentioned putting on every script

```
graphics_toolkit("gnuplot")
```

I wanted to evade doing this all the time by putting

```
c.OctaveKernel.plot_settings = dict(backend='gnuplot')
```

in a octave_kernel_config.py located at /.jupyer

as @dsblank suggested but then the notebook doesn't print anything despite not sending any errors.

Octave 4.4.1 didn't have this plotting related problems, someone knows if notebooks made with the kernel pointing to 4.4.1 would later be usable if oppened but with the kernel pointing to another version of Octave?
