### ISSUE TITLE
kernel doesn't work with octave 6.2

### ISSUE THREAD

**Issue by rolfdstoll** [Calysto/octave_kernel#192]
It looks like the kernel does not work with Octave 6.2.0. OCTAVE_EXECUTABLE and PATH were set correctly according to installation instructions, but without success. The octave kernel chek error message is: [WinError 193] %1 is not a valid Win32 application. But with Octave 5.2 everything works fine. I work with jupyter under winpython 3.9.2 (windows10)

**python -m octave_kernel.check:** 
Octave kernel v0.32.0
Metakernel v0.27.5
Python v3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]

Connecting to Octave...
Octave connection established
[WinError 193] %1 ist keine zulässige Win32-Anwendung

**Comment by rolfdstoll** [comment]
Problem resolved.
Octave 6.2.0 and winpython 3.9.4 completely reinstalled. Path and environment variable set:
Path —>D:\Octave\Octave-6.2.0\mingw64\bin
OCTAVE_EXECUTABLE —> D:\Octave\Octave-6.2.0\mingw64\bin\octave-cli.exe
now it suddenly works with Octave 6.2.0.
Unfortunately, I could not find out the reason for the previous misconduct.

**Comment by dsblank** [comment]
Thanks for the update! Glad you solved it :)
