### ISSUE TITLE
issue connecting to kernel

### ISSUE THREAD

**Issue by n-richardson** [Calysto/octave_kernel#193]
I have an issue when I try to start the octave kernel in a jupyter notebook and the kernel is never able to load which results in the following error.

 raise OSError('octave-cli not found, please see README')

I am trying to run this on windows and on octave-6.2.0. I believe the issue stems from the program not being able to locate octave-cli which I am also unable to run in my windows command prompt. I can run 'octave' as a command and the GUI comes up, but when I try to run octave-cli I get the "not a recognized command".  I don't have that much experience programming, so I am not entirely sure what to do from here.

**Comment by n-richardson** [comment]
Yes, it worked on windows after downgrading! Funny thing though, after I had first encountered this issue, I set up an ubuntu environment in WSL and installed the 6.2.0 version of octave. The Octave-kernel works perfectly there for some reason using the newest version of octave lol.

**Comment by christophbuehler** [comment]
Which version of Octave is currently supported by the kernel?

**Comment by blink1073** [comment]
It is currently tested against 6.4.0 from conda-forge
