### ISSUE TITLE
No output in the IPython 3 notebook

### ISSUE THREAD

**Issue by dcarrera** [Calysto/octave_kernel#2]
Today I installed IPython 3 and the Octave kernel. I can start ipython and select the Octave kernel from the menu. However, it doesn't produce any output. When I type "2+2" I get nothing. Here is what I know:

1) With the Python kernel I do get the "Out[1]: 4". So it's not the UI per se.

2) Octave is running. If I try "plot( [1 2 3], [4 5 6])" I actually get a plot.

3) Initially the window came as a pop-up, but "%inline" fixed it. So it looks like plotting works, and the UI can actually read the plots coming out of Octave.

4) But I still don't get the "Out[]:" lines, even when I run "disp(3)". There are no errors on the notebook, or on the terminal. It's just silent.

**Comment by blink1073** [comment]
I'm calling this fixed, please feel free to reopen if you disagree.
