### ISSUE TITLE
Error: graphics_toolkit: qt toolkit is not available

### ISSUE THREAD

**Issue by adityaapte** [Calysto/octave_kernel#207]
%%octave magic cell produces error while using Octave from Conda. Here are additional details on this topic:
https://octave.discourse.group/t/error-graphics-toolkit-qt-toolkit-is-not-available/2146

**Comment by blink1073** [comment]
Hi @adityaapte, does changing the plot settings to use `gnuplot` work for you?  https://github.com/Calysto/octave_kernel#configuration

**Comment by adityaapte** [comment]
The file ~/.jupyter/octave_kernel_config.py did not exist. So I created one with the following. But the qt error still persists.
```
(test) LMIS0769:software aptea$ cat ~/.jupyter/octave_kernel_config.py
c.OctaveKernel.plot_settings = dict(backend='gnuplot')

```

**Comment by blink1073** [comment]
What `platform` are you using (from `conda info`)?

**Comment by adityaapte** [comment]
active environment : test
    active env location : /Users/aptea/opt/miniconda3/envs/test
            shell level : 2
       user config file : /Users/aptea/.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __osx=10.15.3
       base environment : /Users/aptea/opt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/aptea/opt/miniconda3/pkgs
                          /Users/aptea/.conda/pkgs
       envs directories : /Users/aptea/opt/miniconda3/envs
                          /Users/aptea/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3
Darwin/19.3.0 OSX/10.15.3
                UID:GID : 1941733855:9696963
             netrc file : None
           offline mode : False

**Comment by blink1073** [comment]
Thanks, I'm seeing the same problem in a fresh conda environment.   The `octave` from `conda-forge` doesn't come with the `qt` toolkit, and `gnuplot` doesn't work as-is.  I need to allow you to disable plotting altogether, and also allow it to fail gracefully when you select a backend that doesn't work.  I'm not sure exactly when I'll have a chance to work on this.

**Comment by blink1073** [comment]
I would say downgrade for now until I get a chance to resolve the issue.
