### ISSUE TITLE
Cells cannot output in PDF format

### ISSUE THREAD

**Issue by knuesel** [Calysto/octave_kernel#223]
Would it be possible to support PDF output from cells?

For example executing the following cell:

```
%plot -f pdf

plot(magic(2))
```

gives the error `Cannot embed the 'pdf' image format`.

Having cells with PDF output doesn't sound useful for a notebook but it's actually super useful when using a Jupyter kernel as execution engine to build PDF documents (this is better explained here: https://github.com/JuliaLang/IJulia.jl/issues/1035#issue-1172610713 ).

For example in Python with Matplotlib the following works:

```
%config InlineBackend.figure_formats = ['pdf']

import matplotlib.pyplot as plt

plt.plot([1, 2, 3, 4])
plt.show()
```

(In the notebook GUI it shows a link to view the PDF.)

**Comment by knuesel** [comment]
I think I have a working solution for this and will submit a PR by the end of the week if that's fine with you.

**Comment by blink1073** [comment]
Sounds good, thanks!
