### ISSUE TITLE
PyPI sdist no longer contains tests

### ISSUE THREAD

**Issue by QuLogic** [Calysto/octave_kernel#227]
With 0.35.0, the test file `test_octave_kernel.py` is missing. This used to be there in 0.34.2. I assume this has something to do with the change in build backends, but I'm not familiar enough with hatch to say how.

**Comment by ofek** [comment]
https://github.com/Calysto/octave_kernel/blob/769ade5c0800ac5ef798d3966b38cb6f5f144d87/pyproject.toml#L41-L45

**Comment by blink1073** [comment]
https://github.com/Calysto/octave_kernel/releases/tag/v0.35.1

**Comment by QuLogic** [comment]
Thanks! Works well.
