### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by gmur24** [Calysto/octave_kernel#24]
I cannot install. I just followed the tutorial. I have GNU Octave, version 3.8.0 Copyright (C) 2013. I have Jupyter but after pip install octave_kernel and even upgraded metakernel . Still not working

![image](https://cloud.githubusercontent.com/assets/13022982/11454112/396aa09a-965d-11e5-8237-7e9b535ce814.png)

**Comment by dsblank** [comment]
Looks like you haven't installed octave.

**Comment by gmur24** [comment]
i did using this http://sourceforge.net/projects/octave/files/Octave%20MacOSX%20Binary/2013-12-30%20binary%20installer%20of%20Octave%203.8.0%20for%20OSX%2010.9.1%20%28beta%29/

**Comment by gmur24** [comment]
How should I install it then?

**Comment by dsblank** [comment]
It should be in your PATH so that you can run `octave` at the prompt. Or perhaps you can give the full path to the executable in the kernel.json.

**Comment by blink1073** [comment]
Closing due to lack of response, feel free to reopen.
