### ISSUE TITLE
_make_figs creates or modifies global variable h

### ISSUE THREAD

**Issue by albertoruiz** [Calysto/octave_kernel#25]
https://github.com/Calysto/octave_kernel/blob/master/octave_kernel.py#L170

**In[1]: whos**
Variables in the current scope:

   Attr Name            Size                     Bytes  Class
   ==== ====            ====                     =====  ===== 
        ans             1x70                       757  cell
        figHandles      0x1                          0  double

Total is 70 elements using 757 bytes

**In[2]: plot(1:10)**

**In[3]: whos**
Variables in the current scope:

   Attr Name            Size                     Bytes  Class
   ==== ====            ====                     =====  ===== 
        ans             1x70                       757  cell
        fig             1x1                          8  double
        figHandles      1x1                          8  double
        filename        1x29                        29  char
        h               1x1                          8  double

Total is 102 elements using 810 bytes
 
**In[4]: h**
h =  1

**Comment by blink1073** [comment]
Fixed in 339a3e0, released as `0.13.2`, thanks!
