### ISSUE TITLE
Enhancement: Support for LaTeX in Markdown cells

### ISSUE THREAD

**Issue by sornars** [Calysto/octave_kernel#26]
It would be great if you were able to use LaTeX in the Markdown cells and output the correct images. I'm not sure if this is the responsibility of the kernel, but this feature doesn't seem work with the iOctave kernel while it does with the iPython kernel. 

I'd be happy to work on this if anyone is able to point me in the right direction on how to best go about enabling this.

**Comment by blink1073** [comment]
Hi @sornars, the markdown cell type should work independently of the code cells, and not depend on the kernel.  I tried the following in an Octave notebook markdown cell, and it rendered appropriately: `$$c = \sqrt{a^2 + b^2}$$`.

**Comment by sornars** [comment]
I see you are correct - I had tried that but it wasn't working in one notebook but a brand new notebook is rendering this correctly. I'll chalk this up to an issue on my end.

Apologies for the confusion - closing this issue now.
