### ISSUE TITLE
For loop

### ISSUE THREAD

**Issue by adeliz** [Calysto/octave_kernel#27]
Hi,

I installed jupyter 4.0.6 (Python 2.7.10 |Anaconda 2.4.0 (64-bit)), octave 4.0.0 and the octave_kernel on Windows

I can run code samples from [your notebook](http://nbviewer.ipython.org/github/Calysto/octave_kernel/blob/master/octave_kernel.ipynb) but when I try to run a for loop,

```
for i = [1,3;2,4]
  disp(i)
endfor
```

 I have the following exception :

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\ipykernel\kernelbase.py", line 212, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Anaconda2\lib\site-packages\ipykernel\kernelbase.py", line 370, in execute_request
    user_expressions, allow_stdin)
  File "C:\Anaconda2\lib\site-packages\metakernel\_metakernel.py", line 337, indo_execute
    retval = self.do_execute_direct(code)
  File "C:\Anaconda2\lib\site-packages\octave_kernel.py", line 88, in do_execute_direct
    resp = super(OctaveKernel, self).do_execute_direct(code)
  File "C:\Anaconda2\lib\site-packages\metakernel\process_metakernel.py", line 61, in do_execute_direct
    output = self.wrapper.run_command(code.rstrip(), timeout=None)
  File "C:\Anaconda2\lib\site-packages\metakernel\replwrap.py", line 136, in run_command
    self._expect_prompt(timeout=-1)
  File "C:\Anaconda2\lib\site-packages\metakernel\replwrap.py", line 101, in _expect_prompt
    timeout=timeout)
  File "C:\Anaconda2\lib\site-packages\metakernel\pexpect.py", line 1649, in expect
    timeout, searchwindowsize, async)
  File "C:\Anaconda2\lib\site-packages\metakernel\pexpect.py", line 1670, in expect_list
    return exp.expect_loop(timeout)
  File "C:\Anaconda2\lib\site-packages\metakernel\pexpect.py", line 232, in expect_loop
    return self.timeout(e)
  File "C:\Anaconda2\lib\site-packages\metakernel\pexpect.py", line 197, in timeout
    raise TIMEOUT(msg)
TIMEOUT: <metakernel.pexpect.spawnu object at 0x0000000003D35358>
version: 3.3
command: C:\Octave\Octave-4.0.0\bin\octave.EXE
args: ['C:\\Octave\\Octave-4.0.0\\bin\\octave.EXE', '--no-gui']
searcher: None
buffer (last 100 chars): u'\n'
before (last 100 chars): u'\n'
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 3440
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
```

Do you have any idea of what's wrong?
Thanks for your help.

**Comment by blink1073** [comment]
Hmm, this might be a line endings issue, I ran that code snippet just fine on my OSX machine.  Can you try editing `C:\Anaconda2\lib\site-packages\metakernel\replwrap.py` as follows?

```diff
--- a/metakernel/replwrap.py
+++ b/metakernel/replwrap.py
@@ -64,6 +64,8 @@ class REPLWrapper(object):
             self.child.setecho(False)
             self.child.waitnoecho()

+        self.child.linesep = '\n'
+
         self.echo = echo
         self.prompt_emit_cmd = prompt_emit_cmd
```

**Comment by adeliz** [comment]
Unfortunatly, I still get the same error.
I also tried with ```'\r\n'```

**Comment by blink1073** [comment]
Hmm, perhaps try with just `\r` for good measure?

**Comment by adeliz** [comment]
Still no luck with ```\r```... it even breaks other cells...

But If I set the code on one line, I get the right output.
```
for i = [1,3;2,4]  disp(i); endfor
```

**Comment by blink1073** [comment]
Let's try this:

```diff
diff --git a/octave_kernel.py b/octave_kernel.py
index f1ddb2c..084cb0e 100644
--- a/octave_kernel.py
+++ b/octave_kernel.py
@@ -70,6 +70,7 @@ class OctaveKernel(ProcessMetaKernel):
                            prompt_emit_cmd=prompt_cmd)

     def do_execute_direct(self, code):
+        code = code.splitlines().join(os.linesep)
         if self._first:
             self._first = False
             if sys.platform == 'darwin':
```

**Comment by blink1073** [comment]
Where you may want to play with the join character.

**Comment by adeliz** [comment]
I guess the code should be :
```code = (os.linesep).join(code.splitlines())```
but, any way, I still get the same error message.

I also tried to set the code directly in the ```do_execute_direct``` method.

    super(OctaveKernel, self).do_execute_direct("""
        for i = [1,3;2,4]
          disp(i)
        endfor""")
but no more success...

Is it a metakernel issue?

**Comment by blink1073** [comment]
Hmm, you could try `pip install -U metakernel` and see if that helps, I recently updated it.

**Comment by adeliz** [comment]
...in fact, I already tried that but...

```Requirement already up-to-date: metakernel in c:\anaconda2\lib\site-packages```

Does metakernel write a temporary file, with code inside, before to launch the octave command?
So I could see what is exactly used with octave.exe...

**Comment by blink1073** [comment]
It keeps an octave session open and is piping commands using stdin/stdout.

**Comment by adeliz** [comment]
I tried to dig deeper in the code (First experience with Python!) and found that Pexpect could be the problem

Here is the line I found throwing the error message
```self.child.expect([self.prompt_regex, self.continuation_prompt_regex],
                                      timeout=timeout)```
https://github.com/Calysto/metakernel/blob/master/metakernel/replwrap.py#L100-L101

On the Pexpect docs, it's written :
> As of version 4.0, Pexpect can be used on Windows and POSIX systems. However, pexpect.spawn and pexpect.run() are only available on POSIX, where the pty module is present in the standard library. 

Not sure, it can works on Windows....
Besides, it looks like Metakernel is using version 3.3...

**Comment by blink1073** [comment]
We're using a forked version of 3.3, which we modified to add some functionality, most of it for Windows.

**Comment by adeliz** [comment]
Ok so I continue to investigate...

**Comment by profbrady** [comment]
I am having the same problems with `for` loops in Windows. I can run the following loop fine in OS X and Ubuntu, but not Windows. I have everything up to date; octave_kernel 0.15, metakernel 0.12, etc.
```
clear
format long
n=10
for j=2:n+1
  x(1)=0;
  for i=2:j;
    x(j)=sqrt(2+x(j-1));
  end
  
end
x(1)=[];
prod(x/2)
```

A simpler loop does not work either.

```
clear
for i=1:5
  x=x+i;
end
x
```
I won't introduce loops in class for a few weeks, but when I do I want the Windows users to still be able to use Jupyter and have to switch to the native Octave interface.

Brian

**Comment by blink1073** [comment]
I've got streaming output and for loops working and tested on Windows 7 and OSX, please try `pip install -U octave_kernel`.

**Comment by profbrady** [comment]
Works for me on Windows 10, OS X El Capitan, and Ubuntu 14.04. Thanks.

**Comment by blink1073** [comment]
Excellent, I'll call this one closed.  @adeliz, feel free to reopen if you find it doesn't work for you.

**Comment by adeliz** [comment]
It also works for me. Thanks!
