### ISSUE TITLE
octave kernel with conda installation issue

### ISSUE THREAD

**Issue by ssherwani** [Calysto/octave_kernel#28]
I can't get Octave to work inside Jupyter. 
Every time I create an Octave notebook via Jupyter gui, the octave kernel dies, and I get this "octave-gui.exe Entry point Not found" error. 

![image](https://cloud.githubusercontent.com/assets/1661101/11723421/61ba4022-9f3c-11e5-9dc8-8aa01575277b.png)

![image](https://cloud.githubusercontent.com/assets/1661101/11723531/e973c786-9f3c-11e5-8371-d81f8185b238.png)

![image](https://cloud.githubusercontent.com/assets/1661101/11723658/82ac7d26-9f3d-11e5-9ccc-0a229046b52e.png)

I am on a windows 7 box with Anaconda package manager and Python 3.
And I installed octave_kernel using 'pip install octave_kernel'.

**Comment by blink1073** [comment]
Do you have an `OCTAVE_EXECUTABLE` environment variable set?

**Comment by ssherwani** [comment]
Yes!

![image](https://cloud.githubusercontent.com/assets/1661101/11725645/b4794932-9f48-11e5-8592-8c6d874691bb.png)

**Comment by blink1073** [comment]
Hmm, can you set it to point to /bin/octave-cli-4.0.0.exe?

**Comment by ssherwani** [comment]
I did. It didn't seem to make any difference.

![image](https://cloud.githubusercontent.com/assets/1661101/11726034/abf6c47c-9f4a-11e5-882e-0903fad069e1.png)

**Comment by blink1073** [comment]
Are you able to run that command from the command line without the dll error?

**Comment by ssherwani** [comment]
Yes!


![image](https://cloud.githubusercontent.com/assets/1661101/11726283/ebf7b5a8-9f4b-11e5-9930-643b37ea36c0.png)

**Comment by blink1073** [comment]
Ah, looking at your original output again, it is not finding the `OCTAVE_EXECUTABLE` variable, since is calling `octave` and not your full file path.  You're launching `jupyter notebook` from this same terminal where you've set the variable?

**Comment by ssherwani** [comment]
Yes! 

![image](https://cloud.githubusercontent.com/assets/1661101/11726675/c356f684-9f4d-11e5-813b-65411cd041bc.png)

**Comment by blink1073** [comment]
Can you try setting it to a Windows style path?

**Comment by ssherwani** [comment]
I did. Nothing changed.

![image](https://cloud.githubusercontent.com/assets/1661101/11727925/dc6a2e50-9f54-11e5-92b3-442262ceb5c3.png)

**Comment by blink1073** [comment]
You might want to try deleting that `activity_magic.py` file, it looks like it is not Windows-compatible.

**Comment by dsblank** [comment]
On Thu, Dec 10, 2015 at 4:18 PM, Steven Silvester <notifications@github.com>
wrote:

> You might want to try deleting that activity_magic.py file, it looks like
> it is not Windows-compatible.
>

I saw that; I'll hid that import for Windows users. But it shouldn't have
any effect on this issue, I don't think.

**Comment by blink1073** [comment]
Hi @ssherwani, do you mind trying again with the latest release (0.14)?

**Comment by melorca** [comment]
Hello, I ran into a similar problem, I still got the magic error, but `2+2` and `plot(1:5)` worked on the notebook.
I used:  `set OCTAVE_EXECUTABLE=C:\\Octave\\Octave-4.0.0\\bin\\octave-cli.exe`

I just installed today using pip

Thanks!

**Comment by murych** [comment]
@melorca thanks for solution :v:

**Comment by mwickert** [comment]
I am running Octave-4.0.1 on Windows 10 and find that setting a windows environment variable such as

`set OCTAVE_EXECUTABLE=C:\\Octave\\Octave-4.0.0\\bin\\octave-cli.exe`

or

`set OCTAVE_EXECUTABLE=C:\\Octave\\Octave-4.0.0\\bin\\octave-cli-4.0.1.exe`

both work almost perfectly. The serious exception is that when an octave run-time error, as in improper octave syntax, occurs the expected error message appears in the notebook, but then the kernel shows a long processing time, then times out, and new input cannot be processed unless the kernel is restarted. I can attach the output from the terminal window to explain further. I am using Anaconda.

**Comment by blink1073** [comment]
Hi @mwickert, this is a known limitation of working on Windows.  Octave thinks it is connected as a `pty`, which is not supported on Windows, which ends up causing a forced disconnect of the session when ther e is a syntax error.

**Comment by mwickert** [comment]
OK, I see. I have this set up on Ubuntu and have seen no such issues. I guess this is the environment I should work with for now, as an occasional syntax is inevitable with my typing skills. Perhaps this will be resolved in the future?

**Comment by blink1073** [comment]
I honestly have no idea what to do about it, it has plagued me for years.  One option is to use Qt and QProcess, but that is a huge dependency.

**Comment by mwickert** [comment]
I appreciate your rapid response and now knowing the limitations of this interface. I still like what this has to offer, as I am a big fan of the Jupyter notebook for Python.

**Comment by PierUU** [comment]
Hi, any update on this problem ?

**Comment by blink1073** [comment]
Hi @PierUU, sorry, no, the underlying issue remains.

**Comment by PierUU** [comment]
@blink1073, on which side (Jupyter, octave_kernel, Octave) something should/could be corrected/changed to fix this ? Is there a bug report opened somewhere ?

**Comment by blink1073** [comment]
See for example #34.

**Comment by blink1073** [comment]
Closing this one due to lack of response.  The Windows error-handling is fixed in v0.19.

**Comment by PierUU** [comment]
Well done !!

**Comment by AchimTuran** [comment]
Hi guys,

if you use `setx OCTAVE_EXECUTABLE "<path\to\octave>\mingw64\bin\octave-cli.exe` you only have to set the variable once. And don't foget to restart you conda command line terminal. ;-)
