### ISSUE TITLE
'ascii' codec can't encode character

### ISSUE THREAD

**Issue by thalesmaoa** [Calysto/octave_kernel#29]
When I try to print some text with accent it throw an error:

printf('Área superficial equivalente a %.3f mm^{2}', 1.234);

'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)

I have no idea how to fix it.

lang='pt_BR.utf-8'

**Comment by blink1073** [comment]
Hi @thalesmaoa, thanks for the report.  If you run `pip install -U metakernel`, this issue should be resolved.

**Comment by thalesmaoa** [comment]
Thank you!
