### ISSUE TITLE
No Octave kernel choice in Jupyter after install

### ISSUE THREAD

**Issue by profbrady** [Calysto/octave_kernel#32]
Help. I have an Ubuntu 14.04 VM on my Mac to test the installation of Anaconda3 with Jupyter and octave_kernel. I ran the Anaconda3 installer and changed the .bashrc to inlcude the path and set my python3 alias to match the Anaconda python3 executable. Ran `conda install jupyter`. Ran `pip install metakernel` and `pip install octave_kernel` and both ran with no errors. However, when I start Jupyter I only have the choice of a Python3 kernel. What went wrong? How can I get an Octave kernel selection?

Brian Brady

**Comment by hail-seitan** [comment]
I had the same issue on Linux Mint 17.1 64-bit, conda 3.19.0 - though I don't think I got any `pip install ...` errors. My R kernel works fine, but Octave doesn't show up in the Jupyter notebooks selection.

**Comment by dsblank** [comment]
You can use "jupyter kernelspec list" to see what and where kernels are
installed.

**Comment by profbrady** [comment]
I seem to have stumbled across a solution. I put the following in `~/.local/share/jupyter/kernels/octave/kernel.json`

>{"argv":
> ["/home/{username}/anaconda3/bin/python",
> "-m", "octave_kernel",
>"-f", "{connection_file}"],
>"codemirror_mode": "Octave",
>"display_name": "Octave",
>"language": "octave"
>}

Initially I put this in `~/.ipython/kernels/octave/kernel.json` but it did not seem to work. I removed that directory and found the other location by accident, but it worked.

I installed Octave 4.0 but made sure that `octave` pointed to `octave-cli` not the gui version. Everything works now.

Brian Brady

**Comment by blink1073** [comment]
Hi @profbrady, we were relying on a non-wheel install to install the kernel spec, but pip has started converting tarballs to wheels before installing them.  I released a new version with a 2-step installation method that works around the problem (see the new readme).

**Comment by leftaroundabout** [comment]
After installing the Octave kernel, I also didn't get an `Octave` option in the `New` menu. However, it turned out that the Octave kernel did work just fine, it just wasn't listed &ndash; I could  start `jupyter console --kernel octave` and also open existing Octave notebooks. Only _after that_, Octave now also shows up as a `New` option.

Strange but, oh well, it works now.

**Comment by blink1073** [comment]
Hi @leftaroundabout, agreed, do you now see it in `jupyter kernelspec list`?

**Comment by leftaroundabout** [comment]
@blink1073 I saw it it `jupyter kernelspec list` right from the start, just not in the `New` menu of the browser window of `jupyter notebook`.

**Comment by blink1073** [comment]
Wow, can't say I know what that could mean.

**Comment by RicardoGranados** [comment]
Hello, I have installed with conda the octave kernell. 
jupyter kernelspec list
Available kernels:
  octave     /home/kiro/.local/share/jupyter/kernels/octave
  python3    /home/kiro/.local/share/jupyter/kernels/python3

When I do jupyter notebook I received
[nb_conda_kernels] enabled, 3 kernels found
and in the browser I can find the Octave Kernel but if I try to launch the kernel the GUI of Octave executes and Jupyter does not work with Octave. 

I am using Ubuntu 16.04
anaconda  with python 3.5
jupyter 4.3


I am kind of new with Linux and Jupyter. But I believe is something like ProfBrady said before about pointing to octave-cli and not octave but really don't know how to do that.
Thank you very much

**Comment by blink1073** [comment]
Hi @RicardoGranados, what is the output of `which octave; which octave-cli; octave --version`?

**Comment by RicardoGranados** [comment]
Hi @blink1073  thank you for answering, I was playing this morning trying to fix, I was trying to install with 

`pip install octave_kernel
python -m octave_kernel.install`

But then I tried to instal directly with the oct2py lib,
`$ conda install -c conda-forge oct2py`

And it is working now, I can plot and work everything in Jupyter at least basic functions and ploting, have not tried anything complex.

But if you could give me a hint about what was happening I would appreciate it. Answering your questions:

which octave 
    /usr/bin/octave
which octave-cli
    /usr/bin/octave-cli
octave --version
    /usr/bin/octave

Thank you, and sorry for not trying the other way before asking.
Cheers.

**Comment by blink1073** [comment]
Hi @RicardoGranados, I honestly do not know why it would not have worked the first time, I would have needed more debug information about your previous install.

**Comment by AllenDowney** [comment]
I am having this problem with Anaconda on Linux Mint 19.1.

I created a fresh environment and installed octave and octave-kernel from conda-forge:

```
conda install -c conda-forge octave
conda install -c conda-forge octave_kernel
```

Now I have octave:

```
$ which octave; which octave-cli; octave --version
/home/downey/anaconda3/envs/ModSimMatlab/bin/octave
/home/downey/anaconda3/envs/ModSimMatlab/bin/octave-cli
GNU Octave, version 4.2.1
```

And it's on my list of kernels:

```
$ jupyter kernelspec list
Available kernels:
  vpython    /home/downey/.local/share/jupyter/kernels/vpython
  octave     /home/downey/anaconda3/envs/ModSimMatlab/share/jupyter/kernels/octave
  python3    /home/downey/anaconda3/envs/ModSimMatlab/share/jupyter/kernels/python3
```

But when I launch Jupyter, it's not on the New menu, and if I open a notebook that wants the Octave kernel, it says there is no such kernel.  The issue is the same in Jupyter Notebook and JupyterLab.

@dsblank Any help you can provide would be appreciated!  I am trying to write installation instructions that readers can follow, so trying to keep it simple.

**Comment by dsblank** [comment]
I don't use conda very often, but I can't think of a reason why you would see it in the kernelspec list, but it wouldn't be in the  New menu. 

You might inspect the file under `/home/downey/anaconda3/envs/ModSimMatlab/share/jupyter/kernels/octave` and see if the contents look right. There should be a kernel.json file and maybe some png files for the logo. The .json file should have an argv section that should give the args for executing octave. You could check the permissions on that file. 

@blink1073 any other ideas?

**Comment by AllenDowney** [comment]
Thanks for the quick reply.  Here's what in that directory:

```
(base) downey@rocky:~/anaconda3/envs/ModSimMatlab/share/jupyter/kernels
$ ls octave
kernel.json  logo-32x32.png  logo-64x64.png
$ more octave/kernel.json 
{
    "argv": ["python",
             "-m", "octave_kernel",
             "-f", "{connection_file}"],
    "display_name": "Octave",
    "mimetype": "text/x-octave",
    "language": "octave",
    "name": "octave"
}
```

Looks right to me.

**Comment by dsblank** [comment]
A couple of other things to try:

1. You can explicitly set `OCTAVE_EXECUTABLE` before starting jupyter, giving it the full path to the octave-cli, like `export OCTAVE_EXECUTABLE=/my/path/to/octave-cli`
2. can you run `jupyter console --kernel=octave` ? Does that work? I think it has a `--debug` flag too you could try.

**Comment by AllenDowney** [comment]
Here's what I get from `jupyter console`:

```
$ jupyter console --kernel=octave
Traceback (most recent call last):
  File "/home/downey/anaconda3/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/home/downey/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/downey/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-116>", line 2, in initialize
  File "/home/downey/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/downey/anaconda3/lib/python3.6/site-packages/jupyter_console/app.py", line 142, in initialize
    self.init_shell()
  File "/home/downey/anaconda3/lib/python3.6/site-packages/jupyter_console/app.py", line 109, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/home/downey/anaconda3/lib/python3.6/site-packages/jupyter_client/consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "/home/downey/anaconda3/lib/python3.6/site-packages/jupyter_client/consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/home/downey/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/downey/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/downey/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/downey/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 236, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named octave
```

So at least that's consistent.  I will try setting `OCTAVE_EXECUTABLE` and report back.

**Comment by AllenDowney** [comment]
Setting `OCTAVE_EXECUTABLE` makes no difference.

```
$ export OCTAVE_EXECUTABLE=/home/downey/anaconda3/envs/ModSimMatlab/bin/octave
$ echo $OCTAVE_EXECUTABLE 
/home/downey/anaconda3/envs/ModSimMatlab/bin/octave
$ jupyter console --kernel=octave
Traceback (most recent call last):
 ...
jupyter_client.kernelspec.NoSuchKernel: No such kernel named octave
```

**Comment by dsblank** [comment]
Well, all of that is consistent, but alas does not solve the mystery. I think you can supply a `--debug` when attempting to run the console, to show where it is searching for kernels.

Also, I think anaconda has a special way of installing kernels involving "nb_conda_kernels" (eg, https://stackoverflow.com/questions/39604271/conda-environments-not-showing-up-in-jupyter-notebook ).

**Comment by blink1073** [comment]
@profbrady, do you have `jupyter` installed in that environment?  It looks like from the traceback that it is using `jupyter` from the root conda environment.

**Comment by Pranav-Sureshp** [comment]
You need to install Jupiter on the new environment. Else it won't work
```
conda install -c anaconda jupyter
```
