### ISSUE TITLE
License

### ISSUE THREAD

**Issue by runical** [Calysto/octave_kernel#35]
Hey, I'm trying to package this software to put on the AUR. Could you clarify which license this software is under?

**Comment by blink1073** [comment]
Hi @runical, I'm using `flit` to distribute the package to PyPI, the license is here: https://github.com/Calysto/octave_kernel/blob/master/flit.ini#L10.

**Comment by runical** [comment]
Ah, totally missed that. Thanks for the clarification.

**Comment by runical** [comment]
I think this can be closed now. Thanks again.
