### ISSUE TITLE
'ascii' codec can't encode character u'\u22c5' in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by williamstein** [Calysto/octave_kernel#37]
A user reports here http://ask.sagemath.org/question/32507/error-when-perform-symbolic-calculation-in-octave-of-sage/ that when using the Octave Jupyter kernel in SageMathCloud with this input:

```
pkg load symbolic
syms x
f = sin(x)^2;
diff(f)
```

they get the error in the description above.    I easily replicated this problem:  https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-02-09-185227-octave-symbolic.html

Do other people see this?   If so, any suggestions.  If not, want any more details (I run SageMathCloud).

**Comment by blink1073** [comment]
Hi @williamstein, I'm afraid I'll need more information.  I was able to run the snippet from both Python 2.7 and 3.4 notebooks.  I'm using OSX 10.11.3, with version `0.15.3` of the kernel.

**Comment by williamstein** [comment]
Thanks for checking.  I've made a ticket for us (SageMathCloud) here, since maybe it is more our problem: https://github.com/sagemathinc/smc/issues/415

I'll close this one since it's not some general problem with the octave jupyter kernel, and I don't know when I'll get to look into this again.
