### ISSUE TITLE
Another encode character problem

### ISSUE THREAD

**Issue by thalesmaoa** [Calysto/octave_kernel#39]
Hi, I'm just trying to plot, but can't get it right.

```legend('Isentrópica', 'Adiabática', 'Venson', 'Location', 'NorthWest');
ylabel('Potência [W]'); xlabel('Tempo [s]');```

![](http://s13.postimg.org/om5w7b0yf/Captura_de_tela_de_2016_03_22_19_26_29.png)

Metakernel updated.

**Comment by blink1073** [comment]
This could be a limitation of gnuplot, I just tried the following from an `octave` session:  `plot([1,2,3]);ylabel('Potência [W]')`:

<img width="568" alt="screen shot 2016-03-23 at 6 32 08 am" src="https://cloud.githubusercontent.com/assets/2096628/13983940/00234b0c-f0c1-11e5-88d8-fa624cb995c3.png">

**Comment by thalesmaoa** [comment]
I have tested, but now I figured:

```plot([1,2,3]);ylabel('Potência [W]');```

![](http://s13.postimg.org/v88iy67br/Captura_de_tela_de_2016_03_23_10_07_20.png)

I remembered that octave 4 does not come with gnuplot by default for opengl support.

```
octave:2> available_graphics_toolkits ()
ans = 
{
  [1,1] = fltk
  [1,2] = gnuplot
}
octave:3> graphics_toolkit ("gnuplot");
octave:4> plot([1,2,3]);ylabel('Potência [W]'); 
```
![](http://s13.postimg.org/hpx1855sn/Captura_de_tela_de_2016_03_23_10_08_09.png)

Is there a way to set `fltk` in metakernel?

This toolkit set has also a bug. Once I set it to gnuplot, it doesn't return to fltk, unless I re-open the process.

**Comment by blink1073** [comment]
Does it work for you if you comment out this line?: https://github.com/Calysto/octave_kernel/blob/master/octave_kernel/kernel.py#L163

**Comment by thalesmaoa** [comment]
Unfortunately, not.

I will look for a way to fix in gnuplot and report back.

**Comment by thalesmaoa** [comment]
Tried lot of fixes, but none worked. Now I remember why I quit gnuplot.

I know nothing about metakernel. Is there a way to enable debbug so I can trace why 'fltk' is not working?

![](http://s21.postimg.org/mutdf00sn/Captura_de_tela_de_2016_03_23_12_50_10.png)

**Comment by blink1073** [comment]
`fltk`'s event loop does not play well with Python, I had to abandon it a long time ago when I wrote `oct2py`.

**Comment by thalesmaoa** [comment]
Now I'm confused:

When using oct2py:

![](http://s30.postimg.org/qsfroshlt/Captura_de_tela_de_2016_03_23_14_49_30.png)
![](http://s30.postimg.org/s8ra6xkip/Captura_de_tela_de_2016_03_23_14_50_23.png)

It seems to be an export problem with gnuplot as well, but exporting with svg works great. And better looking.

But when I try with octave_kernel
![](http://s22.postimg.org/ev5rfn2e9/Captura_de_tela_de_2016_03_23_14_53_31.png)

I get fltk working commenting invisible property as well, but I still get the same character encoding error.

**Comment by blink1073** [comment]
It looks like the `%plot` magic isn't working properly, I'll dig in to that.

**Comment by blink1073** [comment]
@thalesmaoa, what OS are you using?  If it is OSX, the `%plot` magic should be fixed.

**Comment by thalesmaoa** [comment]
``` 
$ uname -a

Linux 3.19.0-47-generic 14.04.1-Ubuntu SMP Mon Jan 18 16:09:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Can I help somehow?

**Comment by blink1073** [comment]
You could try adding this debug statement to see what format is being used:

```diff
diff --git a/octave_kernel/kernel.py b/octave_kernel/kernel.py
index 0abbc04..d043e77 100644
--- a/octave_kernel/kernel.py
+++ b/octave_kernel/kernel.py
@@ -194,6 +194,7 @@ class OctaveKernel(ProcessMetaKernel):
                 close(_handle);
             end;
             """ % (plot_dir, self._plot_fmt)
+            print(self._plot_fmt)
             super(OctaveKernel, self).do_execute_direct(cmd.replace('\n', ''))

     def _fix_gnuplot_svg_size(self, image, size=None):
```

**Comment by thalesmaoa** [comment]
```
In[1]: plot(1);
png
png
```

```
In[2]: %plot -f svg
         plot(1);

svg
svg
argument of type 'NoneType' is not iterable
```

**Comment by blink1073** [comment]
Hmm, how about this:

```diff
diff --git a/octave_kernel/kernel.py b/octave_kernel/kernel.py
index 0abbc04..ca439b4 100644
--- a/octave_kernel/kernel.py
+++ b/octave_kernel/kernel.py
@@ -110,6 +110,7 @@ class OctaveKernel(ProcessMetaKernel):
             width, height = 0, 0
             for fname in os.listdir(plot_dir):
                 filename = os.path.join(plot_dir, fname)
+                print(filename)
                 try:
                     if fname.lower().endswith('.svg'):
                         im = SVG(filename)
```

**Comment by thalesmaoa** [comment]
Just went a bit further and found that SVG has None attribute size.

```
self.plot_settings['size']
```
Is none.

```
if ',' in self.plot_settings['size']:
```
Throw an error.

If I comment this line it runs ok but with ugly fonts and size. Now I understand the need of a fix_size function, but couldn't fix it.

Still looking where the attribute size come from.

**Comment by thalesmaoa** [comment]
Ok, I have dig a bit more and found some good infos:
Question: How do you post the diff?
Just want SVG by default, but it brings some problems.
```
if sys.platform == 'darwin' or sys.platform == 'linux2':
             # There is a bug here
             # If the first line is %plot -f png, it prints svg
             # If first plot is SVG, size is set, if changed to png and back, not
             # Ex: %plot -f png  %plot -f svg it lost size settings
```
Fix the None variable.
```
                         if self.plot_settings['size'] == None:
                             width, height = None, None
                         elif ',' in self.plot_settings['size']:
```
Minidom has problems with unicode
```
 # Minidom does not support parseUnicode, so it must be decoded to accept unicode characters
(svg,) = minidom.parseString(image.encode('utf-8')).getElementsByTagName('svg')
```
Setting graph with viewbox is letting it too small.
Also, the font are bigger, I'm just adding a set(0,...) extra.

**Comment by blink1073** [comment]
Thanks @thalesmaoa, these are all great inputs!  To make a diff, run `git diff`, then use the `diff` markdown formatter in the comment.  "```diff"

**Comment by blink1073** [comment]
You can also see the "source code" of any comment by clicking on the pencil icon.

**Comment by thalesmaoa** [comment]
I only have the pencil icon in my posts.
I will try to fix the proposed issues, but it can take some time. It would be nice if you can help me to transfer the nice plot from oct2py.

**Comment by blink1073** [comment]
Ah, I must have access as an admin then.  I was traveling the past two weekends, but I intend to make these updates this weekend.

**Comment by blink1073** [comment]
@thalesmaoa, thank you for your help and your patience, I released 0.15.8 with the fixes.

**Comment by thalesmaoa** [comment]
@blink1073, thanks! I tested and everything is great, but I can't get a nice plot with octave kernel.

![](https://s29.postimg.org/54e1nbpqv/Captura+de+tela+de+2016-04-10+18:39:57.png)

![](https://s29.postimg.org/6kpk5gsnr/Captura+de+tela+de+2016-04-10+18:39:42.png)

Is there a way to change the fonts?

**Comment by blink1073** [comment]
You can change the font as part of the call to `title`:  `title("this is the title", "fontsize", 15)`

**Comment by thalesmaoa** [comment]
I tried changing the font, but I think that is a resolution problem. 
Please take a look to the ticks in my image, you may notice that they are bigger. 
Changing the font was the first step, but couldn't keep it nice.

If I change:
```%plot -s H,W```
The image get better but also bigger. 
This particular issue I couldn't find a walk-around.

**Comment by blink1073** [comment]
I released a temporary work around, you can now specify a resolution as `%plot -r <number>`.  Currently the logic is wrong, in that a lower number gives you a higher resolution, but I will have a permanent fix this weekend.

**Comment by thalesmaoa** [comment]
Sweet! Thank you

**Comment by blink1073** [comment]
New release with the proper fix.  Resolution is ignored for SVG (the default behavior for Octave), but can be set appropriately for PNG.
