### ISSUE TITLE
figures not showing in png format

### ISSUE THREAD

**Issue by oroszl** [Calysto/octave_kernel#44]
Hi,
using the Dockerfile below octave_kernel does not produce figures in png mode only in svg mode.
Weirdly `imshow()` works but `plot()` does not produce any image. Is this some version conflict somewhere ?
I do not have any similar issues with `python` and `matplotlib`.

```
# dockerfile for building the basic image
FROM jupyter/systemuser

MAINTAINER ELTE-KRFT

USER root

ENV SHELL /bin/bash

RUN /usr/bin/apt-get update && \
    apt-get install -y --no-install-recommends ldap-utils zip octave octave-audio octave-biosig octave-gdf octave-image octave-io octave-signal octave-specfun octave-statistics gnuplot && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pip --upgrade

#https://github.com/Calysto/octave_kernel
RUN pip install octave_kernel
RUN python -m octave_kernel.install

#plotly
RUN pip install plotly

#https://github.com/damianavila/RISE
RUN pip install RISE
RUN jupyter-nbextension install rise --py --sys-prefix
RUN jupyter-nbextension enable rise --py --sys-prefix

#https://github.com/ipython-contrib/jupyter_contrib_nbextensions/
RUN pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master
RUN jupyter contrib nbextension install --system --symlink
RUN pip install jupyter_nbextensions_configurator
RUN jupyter nbextensions_configurator enable --system

#https://github.com/jupyter/nbgrader
RUN pip install nbgrader
RUN nbgrader extension install
RUN nbgrader extension activate

#RUN pip install --upgrade

# auth
ADD ldap.conf /etc/ldap/ldap.conf
ADD systemuser.sh /srv/singleuser/systemuser.sh

CMD ["sh", "/srv/singleuser/systemuser.sh"]
```

**Comment by blink1073** [comment]
I have seen the issue before as well locally (not in a Docker container), and can only assume it comes from improper support of the `print` function in Octave.  https://github.com/Calysto/octave_kernel/blob/4cb299ae417f66355d823d21fa0d5849f2963bfd/octave_kernel/kernel.py#L205

**Comment by oroszl** [comment]
so does this mean i should try to down/up grade octave and see what happens ?

**Comment by blink1073** [comment]
It could be related to this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=710272

**Comment by oroszl** [comment]
Well I have played a bit with the suggestions in your previous post but my problem still persists. And as I noted initially I have problem with the png backend. I can produce svg-s without any problem. There is also a strange buffering behavior. 

running a cell containing 
```
%plot inline -f png
plot(rand(10,1))
```
produces nothing.
going back to the cell and editing it to 
```
%plot inline -f svg
plot(rand(10,1))
```
generates two figures. It seems that the figure not plotted survives somewhere in a buffer.

**Comment by blink1073** [comment]
I'm afraid I don't know what else to suggest other than to specify `svg` for all plots.  The setting persists across cells, so you only need to set it once in a notebook.

**Comment by oroszl** [comment]
After installing `ghostscript` as well in the container the issue is resolved!

**Comment by blink1073** [comment]
Great, I'm glad you got it sorted and thanks for reporting back so we know what to try in the future ;).

**Comment by oroszl** [comment]
i tried just to generate a png file in the notebook and it immediately complained that ghostscript is not installed so I thought I give it a shot.. It is strange because I thought installing octave would also install gnuplot and ghostscript but apparently no. Anyway thanks for your suggestions!
