### ISSUE TITLE
ascii encoding problem with special characters

### ISSUE THREAD

**Issue by haraldschilly** [Calysto/octave_kernel#46]
I'm trying to run `printf("ä")` but I get an encoding error by python:

```
'ascii' codec can't encode character u'\xe4' in position 0: ordinal not in range(128)
```

**Comment by blink1073** [comment]
Hi @haraldschilly, can you describe your environment?

I just ran that code using the following environment and the output works:

```bash
$ pip freeze | grep octave
octave-kernel==0.16.0
$ pip freeze | grep notebook
notebook==4.2.0
$ octave -v
GNU Octave, version 4.0.0
$ uname -a
Darwin 0202-ssilvester.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 204
$ ipython
Python 3.4.5 | packaged by conda-forge | (default, Jul  9 2016, 18:00:48)
Type "copyright", "credits" or "license" for more information.
```


<img width="204" alt="screen shot 2016-09-27 at 1 18 05 pm" src="https://cloud.githubusercontent.com/assets/2096628/18887673/a7b9b77e-84ba-11e6-926a-0edcf82ca13d.png">

**Comment by haraldschilly** [comment]
It's the one on https://cloud.sagemath.com

```
octave-kernel==0.14.3 # ok, at least interesting that you have a newer one

notebook==4.2.2

$ octave -v
GNU Octave, version 4.0.0

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily

$ uname -a
Linux compute6-us 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ sage -ipython # just a wrapper around the one inside
Python 2.7.10 (default, Aug 12 2016, 15:31:38)
IPython 4.2.1
```

But anyways, that error message I reported is definitely from Python 2.7, and you're on Python 3. I don't know where exactly, but somewhere needs to be some wrapping to convert the bytes to unicode to get this right. The error is unfortunately just one line -- at least I don't know how to show the full stacktrace to pinpoint where it is unhappy.

**Comment by blink1073** [comment]
I tried in a fresh conda environment with Python 2.7:

```python
In [2]: printf("ä")
      :
ä

In [3]: ones(3)
      :
ans =

   1   1   1
   1   1   1
   1   1   1
```

**Comment by blink1073** [comment]
I'm thinking it may be a stale version issue.

**Comment by blink1073** [comment]
Closing as fixed based on this comment: https://github.com/sagemathinc/smc/issues/953#issuecomment-258463293.  Glad you got it sorted!
