### ISSUE TITLE
Timeouts on long running computations

### ISSUE THREAD

**Issue by ludwigschubert** [Calysto/octave_kernel#48]
I was getting timeouts on long running (multiple minutes) computations, even though they were still healthy.

I hacked around this by setting the default timeout in `pexcept.py` in the `metakernel` package from 30 to 300; but obviously that's not a solution.

Let me know if I can do anything to help track this down—and thanks for your work on this kernel!

**Comment by blink1073** [comment]
Thanks, for the report, fixed in v0.19.
