### ISSUE TITLE
Octave kernel does not show up as an option when creating a new notebook

### ISSUE THREAD

**Issue by G2Jose** [Calysto/octave_kernel#49]
### No option to create a new octave notebook through jupyter

![image](https://cloud.githubusercontent.com/assets/6994514/20269682/4277ee54-aa52-11e6-9d6b-6b9706c8032c.png)

Setup - Ubuntu 14.04, Python 3.5.2, Anaconda 4.2.9, Jupyter 4.2.0
Installed octave_kernel using `pip install octave_kernel && python -m octave_kernel.install`. 

I'm able to see octave when I run `jupyter kernelspec list`
```
➜  ~ jupyter kernelspec list
Available kernels:
  python3    /usr/local/lib/python3.4/dist-packages/ipykernel/resources
  octave     /home/ubuntu/.local/share/jupyter/kernels/octave
```

When I start jupyter using `sudo jupyter notebook` and navigate to the jupyter web page, I only see an option to create a Python3 notebook, and not an octave one. 

I am however able to start a CLI octave console through jupyter using `jupyter console --kernel octave`. 

This is possibly related to https://github.com/Calysto/octave_kernel/issues/32

**Comment by blink1073** [comment]
Hi @G2Jose, can you try `python -m octave_kernel.install --user` and run it again?

**Comment by blink1073** [comment]
@G2Jose, I'm going to close this as answered.  Please feel free to reopen if you come back to this and it does not work.
