### ISSUE TITLE
%%octave doesn't complete 

### ISSUE THREAD

**Issue by josephcslater** [Calysto/octave_kernel#50]
I have MacOS X  10.12.1, octave 4.0.3 installed via `macports`, and `python/jupyter` installed via macports. 

`%load_ext oct2py.ipython`

seems to work fine (finishes without error). However, I can't actually use it. I can't figure out how to figure out what's going on while it hangs. 

```
from oct2py import Oct2Py
oc = Oct2Py()
print(oc.abs(-1))`
```

Works as expected (inside and outside Jupyter). 

How do I diagnose what's going on and try to fix it?

FWIW: same versions installed on Ubuntu 16.10 failed as well, but [differently](https://gist.github.com/josephcslater/86718ae919248ba355fe9587327e67ad).

Hang happens even in a dedicated Octave kernel notebook.

**Comment by blink1073** [comment]
Hi @josephcslater, I can reproduce this issue, and will work on trying to fix it.  The issue is with `oct2py` itself, which is a cousin of this project but does not share any code.

**Comment by josephcslater** [comment]
Yeah, I'm sorry. Somehow I messed up and posted here by accident. I honestly can't even understand how I messed that up, but then noticed the octave_kernel messing up the same way later. Of course, it's likely a change in the behavior of octave I'm guessing.

**Comment by blink1073** [comment]
I think the problem you're seeing in the octave notebook is because you've accidentally used `print()` instead of `disp()`.
