### ISSUE TITLE
shlex strips backslashes from OCTAVE_EXECUTABLE environment variable

### ISSUE THREAD

**Issue by jcb91** [Calysto/octave_kernel#57]
I suppose this may actually be an issue with metakernel, but essentially what happens is:

1. I'm on windows, and don't want all the unix executables provided by octave's mingw added to the default windows path, so I set the environment variable `OCTAVE_EXECUTABLE`. In my case, it would be `C:\Octave\Octave-4.2.0\bin\octave-cli.exe`. This is read directly in [octave_kernel/kernel.py#L294](https://github.com/Calysto/octave_kernel/blob/master/octave_kernel/kernel.py#L294), and passed eventually to [pexpect.popen_spawn](https://github.com/pexpect/pexpect/blob/cb440d20f9dd3488f61d5af8b2f7e8a8bad2c7dd/pexpect/popen_spawn.py).
2. the `shlex.split` call in [pexpect/popen_spawn.py#L43](https://github.com/pexpect/pexpect/blob/cb440d20f9dd3488f61d5af8b2f7e8a8bad2c7dd/pexpect/popen_spawn.py#L43) strips all backslashes, resulting for me in a command path of `C:OctaveOctave-4.2.0binoctave-cli.exe`.
3. I can get this to work by using forward slashes in the `OCTAVE_EXECUTABLE` variable. This is ok for me now, but it would be a good idea to either mention this fact in the readme, or run a
   ```python
   executable = executable.replace(os.path.sep, '/')
   ```
  in octave_kernel to make it work with windows paths.

**Comment by dsblank** [comment]
Your analysis sounds right. Would you be willing to make a PR?

**Comment by blink1073** [comment]
Thanks @jcb91!  I was in the middle of making a release, so I applied your patch.  Released in 0.19.16.

**Comment by dsblank** [comment]
Thanks @blink1073  ! Thanks @jcb91 !

**Comment by jcb91** [comment]
Wow, quick work! Thanks everyone :)
