### ISSUE TITLE
%plot options dont seem to do anything

### ISSUE THREAD

**Issue by DeepHorizons** [Calysto/octave_kernel#58]
When testing the fix for #38, I can't seem to change the format, size, or resolution.

On another note, the figures are different for different plots, but are just small and grayscale.

In addition, the `-h` for help was replaced with `-h` and `-w` for height and width (may be a feature). `--help` prints out a help dialog then raises an error.

**Comment by blink1073** [comment]
Hi @DeepHorizons, I just checked again and the plot options are working for me.  What OS and version of Octave are you using?  The `%plot --help` is definitely a bug.

**Comment by blink1073** [comment]
The `%plot --help` error can be fixed as `pip install -U metakernel`.

**Comment by blink1073** [comment]
I also fixed the handling of resolution - it should work if the size is not specified, which is the behavior when using `print` in `Octave`.   You can update `octave_kernel` and `metakernel` simultaneously as `pip install -U octave_kernel`.

**Comment by DeepHorizons** [comment]
OS is Debian
I'm running Octave 4.0.3, and I updated to `octave_kernel` 0.19.17 and `metakernel` 0.17.4

After fiddling with it, plots do change to the format, but figures do not. They always output png and don't accept any of the other options.

Some example code,
```octave
pkg load signal
x = chirp([0:0.001:2],0,2,500);  # freq. sweep from 0-500 over 2 sec.
Fs=1000;                  # sampled every 0.001 sec so rate is 1 kHz
step=ceil(20*Fs/1000);    # one spectral slice every 20 ms
window=ceil(100*Fs/1000); # 100 ms data window
specgram(x, 2^nextpow2(window), Fs, window, window-step);
```

And the output with attempting to change the format:
![same_output](https://cloud.githubusercontent.com/assets/5551273/21836240/7c34f3fa-d791-11e6-8301-362361905eac.png)

**Comment by blink1073** [comment]
Ah, image objects are saved using `imwrite`.  I will change it so that if you provide any size overrides then it doesn't use `imwrite`.

**Comment by blink1073** [comment]
Also if you provide `svg` it will not use `imwrite` since that only works with `png`.

**Comment by DeepHorizons** [comment]
I'm not too worried about the size,
more about why the images don't look as they did from May of last year.

![good specgram](https://cloud.githubusercontent.com/assets/5551273/13730814/acc011f8-e930-11e5-97be-2929f2c98a07.png)

**Comment by blink1073** [comment]
I agree with you that the `imshow` behavior is too brittle.  What we really need is an `%%imshow filename` magic that displays a file that was written to disk. I'll look into this more over the weekend.

**Comment by blink1073** [comment]
Okay, I think I've got a compromise.  It will use the `imwrite` *only* if the figure contains one axis with one child that is an image, and has no title, xlabel, or ylabel.  Otherwise it will use a plot.  I just need to test it a bit more.
