### ISSUE TITLE
Black plot in the notebook

### ISSUE THREAD

**Issue by elyase** [Calysto/octave_kernel#6]
I am getting a black plot. The plots work ok from the octave console. Also everything else seems to work ok on the notebook. No idea how to debug further. I am on OS X Maverick.

![screen shot 2015-02-07 at 00 05 28](https://cloud.githubusercontent.com/assets/1175888/6089042/18054a88-ae5d-11e4-87fc-e2236b309a66.png)

**Comment by blink1073** [comment]
@elyase, thanks for the feedback!  Can you try the following from an octave prompt and let me know what you get:

```
graphics_toolkit
available_graphics_toolkits
f = figure()
plot([1,2,3])
saveas(f, 'test.png')
```

**Comment by elyase** [comment]
Thanks to you for taking the time! This is the output:

```
octave:1> graphics_toolkit
ans = gnuplot
octave:2> available_graphics_toolkits
ans = 
{
  [1,1] = gnuplot
}
octave:3> f = figure()
f =  1
octave:4> plot([1,2,3])
octave:5> saveas(f, 'test.png')
warning: print.m: fig2dev binary is not available.
Some output formats are not available.
octave:6>
```

I should add that I have just installed octave suing `homebrew`.

**Comment by blink1073** [comment]
Try using `%plot gnuplot` in the kernel before the plot command.  While not ideal, you should be able to view the figure in gnuplot that way.

**Comment by vate01** [comment]
When I use %plot gnuplot, I receive the message: 

'NoneType' object has no attribute 'split'

and the plot is launched outside of the notebook.

Any ideas to solve this issue?

Thanks :)

**Comment by blink1073** [comment]
@vate01, I just pushed a fix, can you try running from the latest `master`?

**Comment by blink1073** [comment]
@elyase, now that I have a Mac I was able to fix your problem as well.  Apparently Octave for Mac does not like `png` files so we now use `svg` by default.

**Comment by vate01** [comment]
Thanks for your quick answer. I did and I get the same result. A screenshot is below:

![captura de pantalla de 2015-05-22 00-56-16](https://cloud.githubusercontent.com/assets/4692079/7763844/82a453cc-001d-11e5-9d76-a98cd487c802.png)

That is, a new windows is launched with the plot but, if I remove the %plot gnuplot, the result is a black box.

Thanks for your time.

**Comment by blink1073** [comment]
@vate01, what operating system are you using?

**Comment by vate01** [comment]
Hello. I'm on ArchLinux, kernel 4.0.4-1-ARCH x86_64. Thanks a lot.

**Comment by blink1073** [comment]
@vate01, can you please try `%plot --format svg`?

**Comment by vate01** [comment]
Black box. The message returned was: 

`'NoneType' object has no attribute 'split'`

I verified, for instance, that command 

`from IPython.display import Image, SVG`

run with no problems in a python shell.

Thanks.

**Comment by blink1073** [comment]
@vate01, I'm not sure why you're still getting that error.  How did you install the library?  If you'd like the latest without cloning, you can use `pip install git+https://github.com/calysto/octave_kernel`

**Comment by vate01** [comment]
Well, no problem. 

In the meanwhile I will be using the (default) octave gui.

![captura de pantalla de 2015-05-22 18-59-37](https://cloud.githubusercontent.com/assets/4692079/7780404/d51627c4-00b4-11e5-9f23-5030a80e7748.png)

I will be attentive to this issue.

Thanks.

**Comment by elyase** [comment]
Sorry for the late replay. I am happy to report that is working ok on OS X. Thanks a lot!!

**Comment by blink1073** [comment]
Great, cheers!

**Comment by santhosh12992** [comment]
@elyase How you made it to work? Can you help me please?
