### ISSUE TITLE
egg.info directory

### ISSUE THREAD

**Issue by SylvainCorlay** [Calysto/octave_kernel#7]
Isn't it common practice to have the `egg.info` directory part of the git repository? This would avoid having the git repo marked as having untracked content when you install it with distutils.

**Comment by blink1073** [comment]
Do you mean for `pip install -e .`?  Unfortunately, that method does not work because the kernel spec needs to be installed in `~/.ipython` and the `install_with_kernelspec` in `setup.py` is only invoked for the `install` command.

**Comment by SylvainCorlay** [comment]
Also that pip generates this content, which makes my git submodule appear as changed. 
Alternatively, this could be added to the .gitignore.

**Comment by blink1073** [comment]
Fixed both problems, thanks!

**Comment by SylvainCorlay** [comment]
thx
