### ISSUE TITLE
Plotting problems (osx)

### ISSUE THREAD

**Issue by brunodigiorgi** [Calysto/octave_kernel#71]
Hi,
I have installed octave 4.0.3, the octave_kernel, and set the environment variable as:
OCTAVE_EXECUTABLE=/Applications/Octave.app/Contents/Resources/usr/bin/octave-cli

The kernel starts up nicely, and I can write for example 
`a = [1, 2, 3]` 
and get the expected output.

However, if I call 
`plot([1, 2, 3], [4, 5, 6])`
I get errors saying:
```
warning: print.m: epstool binary is not available.
Some output formats are not available.
warning: print.m: fig2dev binary is not available.
Some output formats are not available.
warning: print.m: pstoedit binary is not available.
Some output formats are not available.
error: __osmesa_print__: support for offscreen rendering was disabled when Octave was built
error: called from
    __opengl_print__ at line 171 column 7
    print at line 431 column 14
    _make_figures>inner_print at line 127 column 5
    _make_figures>safe_print at line 118 column 5
    _make_figures at line 44 column 13
```

I strongly suspect this is because the binaries epstool, fig2dev, pstoedit are not found by the kernel.
However I have those in the same folder of the OCTAVE_EXECUTABLE. How can I solve this? 

As an ugly temporary fix, I thought I could add that folder (/Applications/Octave.app/Contents/Resources/usr/bin) to my PATH, but if I do that, the plot command hangs forever.

**Comment by brunodigiorgi** [comment]
Update:
I solved the problem by installing the current version of gnuplot (5.0.5) from source (https://sourceforge.net/projects/gnuplot/files/gnuplot/5.0.5/gnuplot-5.0.5.tar.gz/download).

**Comment by blink1073** [comment]
Hi @brunodigiorgi, unfortunately the inline is only as good as our ability to create an image with `print()` in `Octave`, which has proven to be troublesome.

I was able to clean up your example a bit using

```octave
%plot -f png -r 200
plot([1,2,3], [3,4,5], 'DisplayName', 'plot_a');
hold on;
stem([1,2,3], [2,3,1], 'r', 'DisplayName', 'stem_b');
hold off;
xlabel('$t$', 'Interpreter', 'latex');
legend('show')
```

**Comment by brunodigiorgi** [comment]
Yes, I can confirm that with the png format the markers have the expected size. However both latex labels and legend are still problematic. I understand that these issues are actually related to Octave + gnuplot and not to the octave_kernel. Many thanks
