### ISSUE TITLE
Ability to use octave_kernel without gnuplot installed

### ISSUE THREAD

**Issue by shoyer** [Calysto/octave_kernel#74]
This restriction seems overly restrictive. Instead, it would be better to issue an informative error only when a plot is made.

**Comment by blink1073** [comment]
This is based on experience where fltk completely locks the process when a plot window is shown.

**Comment by shoyer** [comment]
So it's difficult to issue that informative error?

An alternative would be an optional flag to allow using octave_kernel without gnuplot. I guess we'd need it in oct2py, too. Otherwise I'm going to need to make a local patch to disable the gnuplot check.

**Comment by blink1073** [comment]
Okay, that's fair.  We'll attempt to set gnuplot and warn if it doesn't exist.  Oct2py is using the OctaveEngine from this library directly, so it will have the same behavior.

**Comment by blink1073** [comment]
Fixed in a74e2dd834c3069c0c3ba8fb9a87d9600e87ee6e, released in v0.25.0.

<img width="756" alt="screen shot 2017-01-28 at 6 18 35 am" src="https://cloud.githubusercontent.com/assets/2096628/22396556/01fa03ca-e522-11e6-89ba-8e918028728d.png">

**Comment by shoyer** [comment]
Thanks @blink1073, I really appreciate it!
