### ISSUE TITLE
Kernel doesn't seem to start on OS X El Capitan

### ISSUE THREAD

**Issue by patricksulin** [Calysto/octave_kernel#75]
Tries to start the Octave kernel, but eventually times out with no response. My IPython, Jupyter and Octave all work fine independently. I have set my OCTAVE_EXECUTABLE.

> jupyter console --kernel octave --debug

[ZMQTerminalIPythonApp] Starting kernel: [u'/Users/patricks/.virtualenvs/pynotebooks/bin/python', u'-m', u'octave_kernel', u'-f', u'/Users/patricks/Library/Jupyter/runtime/kernel-27340.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:62711
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:62708
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:62708
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:62709
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:62709
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:62710
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:62710
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:62712
...
...
RuntimeError: Kernel didn't respond to kernel_info_request

**Comment by blink1073** [comment]
Hmm, I just tried on El Capitan and it is working on my machine (famous last words).  What is the output of `pip list | egrep "octave-kernel|jupyter-client"` and `octave --version`?

**Comment by patricksulin** [comment]
++ pip list | egrep "octave-kernel|jupyter-client"
jupyter-client (4.4.0)
octave-kernel (0.25.1)

 ++ octave --version
GNU Octave, version 4.2.0

I should say that I had the octave kernel working a while ago, but could never get plotting to work with gnuplot and only after updating and re-installing many packages am I running into this problem. So it's almost certainly with my configuration, but there doesn't seem any information from --debug to use to troubleshoot.

**Comment by blink1073** [comment]
Does this work for you from a standard `python` prompt?

```python
from octave_kernel.kernel import OctaveEngine
octave = OctaveEngine()
octave.eval('ones')
```

**Comment by patricksulin** [comment]
I just got it working.  I had added a .octaverc file based on some suggestions I had read and removing that solved it.  Thanks for the quick responses. Looking forward to using Octave in Jupyter!

**Comment by blink1073** [comment]
Do you know what in the `.octaverc` was causing it?
