### ISSUE TITLE
How can I contribute to this project during GSoC??

### ISSUE THREAD

**Issue by thetransformerr** [Calysto/octave_kernel#77]
I can't see many open issues which could be addressed to improve this project, would somebody help me about most wanted improvement in this project.

Thanks

**Comment by blink1073** [comment]
Hi @thetransformerr, I think the kernel is fairly stable, but there are still some issues with plotting support on different platforms.  If you would like to do some research on how to make that work better it would be most appreciated!

**Comment by dsblank** [comment]
Closing, for this summer. Future GSoC can re-open, or  start a new issue.
