### ISSUE TITLE
how do I choose --traditional

### ISSUE THREAD

**Issue by rrtucci** [Calysto/octave_kernel#78]
I tried

!octave --traditional

and it didn't work

**Comment by blink1073** [comment]
There currently isn't a way to pass that information to the kernel.  We could honor an `OCTAVE_CLI_OPTIONS` environment variable, does that sound reasonable?

**Comment by rrtucci** [comment]
Sounds good. At least for me, the ability to run Octave in traditional mode is absolutelyessential. --- notifications@github.com wrote:From: Steven Silvester <notifications@github.com>To: Calysto/octave_kernel <octave_kernel@noreply.github.com>Cc: "Robert R. Tucci" <tucci@ar-tiste.com>,  Author <author@noreply.github.com>Subject: Re: [Calysto/octave_kernel] how do I choose --traditional (#78)Date: Fri, 10 Mar 2017 00:21:15 -0800There currently isn't a way to pass that information to the kernel.  We could honor an OCTAVE_CLI_OPTIONS environment variable, does that sound reasonable?

**Comment by blink1073** [comment]
Available in version `0.26` (`pip install -U octave_kernel`).
