### ISSUE TITLE
cell evaluation bug in octavemagic

### ISSUE THREAD

**Issue by rrtucci** [Calysto/octave_kernel#81]
Octavemagic gives me the following erroneous result
https://github.com/rrtucci/bob-sandbox/blob/master/octavemagic-bug.ipynb
If I try the same thing with octave kernel, it works fine
https://github.com/rrtucci/bob-sandbox/blob/master/octave-kernel-okay.ipynb

**Comment by dsblank** [comment]
That looks like it is either an error in oct2py (a different repo, at https://github.com/blink1073/oct2py) or in IPython itself in parsing the magic.

**Comment by rrtucci** [comment]
dsblank, Thanks for directing me to right repo. I posted the issue there

**Comment by dsblank** [comment]
Thanks!
