### ISSUE TITLE
(octave kernel) plot shows blank in jupyter

### ISSUE THREAD

**Issue by zhangyinsheng** [Calysto/octave_kernel#82]
In octave, plot works fine.
In jupyter, the plot is black. but axes and ticks are show

![default](https://cloud.githubusercontent.com/assets/25282100/24650445/c1d42ed2-195c-11e7-9ac4-a558eb862486.png)

**Comment by blink1073** [comment]
Hi @zhangyinsheng, this is a limitation of the `print` function in Octave used to create the figure.  You can try specifying an svg as `%plot -f svg` or trying another graphics backend in your Octave session.   https://www.gnu.org/software/octave/doc/v4.0.0/Graphics-Toolkits.html

**Comment by zhangyinsheng** [comment]
Thanks for the reply. 
The machine with problem is a vm. I tried another machine (a physical machine), it works fine. 
They both use gnuplot. Still don't know why. But I'll just work around with the physical machine.

**Comment by xfliu** [comment]
After upgrading Ubuntu from 2014.04 to 2016.04, there comes the same problem of black plot.
Before the upgrading. there is no need of input "%plot -f svg". But now it is needed.

So, I am wondering that is there any method to tell Jupyter to add such an  option, i.e., plot as svg,  before running the code?

Best regards!

**Comment by blink1073** [comment]
Hi @xfliu, there is currently no option to persist any settings for the Octave kernel.
