### ISSUE TITLE
install octave_kernel on win 10

### ISSUE THREAD

**Issue by peter73421** [Calysto/octave_kernel#83]
I followed the instruction for installing Jupyter notebook. I'm using Anaconda3 platform, installed GNU Octave. After starting "jupyter notebook" for first time I have no option to use jupyter notebook for Octave therefore I installed octave_kernel but unfortunately after this install the "python.exe" from /Anaconda3 is removed and jupyter notebook can't be started anymore. there is install issue with octave_kernel for Windows 10, Anaconda3, jupyter notebook. it can't be installed on this platform. Is it possible to fix it?

**Comment by blink1073** [comment]
Hi @peter73421, it sounds like we need to do some digging.  What are the outputs of `python --version` and `where pip`?

**Comment by peter73421** [comment]
python --version

```
C:\Anaconda3>python --version
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)
```

where pip
```
C:\Anaconda3>where pip
C:\Python27\Scripts\pip.exe
C:\Anaconda3\Scripts\pip.exe
```

**Comment by peter73421** [comment]
python --version

```
C:\Anaconda3>python --version
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)
```
where pip

```
C:\Anaconda3>where pip
C:\Python27\Scripts\pip.exe
C:\Anaconda3\Scripts\pip.exe
```

**Comment by blink1073** [comment]
Ah, your system `pip` is ahead of the Anaconda one, so the `pip install` put `octave_kernel` in your system location.  You can either add `C:\Anaconda3\Scripts\` to your `PATH` system environment variable or explicitly use `C:\Anaconda3\Scripts\pip.exe install octave_kernel`.  Either way, you then run `python -m octave_kernel.install` to install it.

**Comment by peter73421** [comment]
Thanks for advice, actually jupyter starts but octave_kernel is not starting and Jupyter says "Dead Kernel", so can execute Octave code. Any advice why kernel is not working?

**Comment by blink1073** [comment]
Does the following work from a `python` prompt?

```python
from octave_kernel.kernel import OctaveEngine
engine = OctaveEngine()
engine.eval('ones(1)')
```

**Comment by peter73421** [comment]
```
C:\Anaconda3>python
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from octave_kernel.kernel import OctaveEngine
>>> engine = OctaveEngine()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 143, in __init__
    self.executable = self._get_executable()
  File "C:\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 417, in _get_executable
    raise OSError(msg)
OSError: Octave Executable not found, please add to path or set"OCTAVE_EXECUTABLE" environment variable
>>> engine.eval('ones(1)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'engine' is not defined
>>>

```

**Comment by blink1073** [comment]
Ah, so it can't find `octave.exe`.  You'll have add the path to that file in your `PATH` environment variable (type "environment variable" in the Windows start menu to find the dialog).

**Comment by blink1073** [comment]
(as in, add the path to the folder containing `octave.exe`).

**Comment by peter73421** [comment]
Thanks!!! Now it's working.

```
C:\Anaconda3>python
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from octave_kernel.kernel import OctaveEngine
>>> engine = OctaveEngine()
>>> engine.eval('ones(1)')
'ans =  1\n'
>>> exit()
```

**Comment by blink1073** [comment]
Great!
