### ISSUE TITLE
hosted demo notebook has malicious notebook

### ISSUE THREAD

**Issue by bo01ean** [Calysto/octave_kernel#84]
FYI: When I load the demo notebook, the page attempts to redirect me to some affiliate site.

**Comment by dsblank** [comment]
What notebook? What URL?

**Comment by dsblank** [comment]
If it was because of this https://github.com/unpkg/unpkg.com/issues/31 I think it has been fixed.

**Comment by bo01ean** [comment]
This is no longer happening :)
