### ISSUE TITLE
Display color image in Jupyter notebook

### ISSUE THREAD

**Issue by ghost** [Calysto/octave_kernel#86]
I'm running Jupyter server 5.0.0 with Octave Kernel v0.26.2 running GNU Octave v4.2.1, under  Python 3.5.3. I'm using image pkg and as soon as I want to "imshow" color picture then it's not display correctly. There is some "color cloud"  shown but this is not the picture which is supposed to be loaded. I did try it under regular Octave GUI installation and it just works. So it seems to be an issue of displaying color images. When I load greyscale image it's displayed OK.

**Comment by dsblank** [comment]
Can you attach a picture of this "color cloud"? That might help determine what is wrong.

**Comment by peter73421** [comment]
I see this

![capture](https://cloud.githubusercontent.com/assets/14235529/25533575/58e25772-2c31-11e7-97bb-11a62a86f7be.PNG)

and it should be this
![fruit](https://cloud.githubusercontent.com/assets/14235529/25533592/71a90c7e-2c31-11e7-9980-9b7ecef76f22.png)

**Comment by dsblank** [comment]
Can you post a minimal example code that demonstrates the issue? What is the format of the image I?

**Comment by peter73421** [comment]
```
I = imread ("fruit.png");
imshow(I)
```

**Comment by peter73421** [comment]
![astonmartindb11](https://cloud.githubusercontent.com/assets/14235529/25534437/0c701a3e-2c34-11e7-912f-15be685880f7.jpg)

![capture](https://cloud.githubusercontent.com/assets/14235529/25534405/fa7f4822-2c33-11e7-9d90-c54a53daea4f.PNG)

**Comment by peter73421** [comment]
Reading fruit.png via python/opencv in Jupyter notebook 
![capture](https://cloud.githubusercontent.com/assets/14235529/25537159/b22f9de2-2c3d-11e7-924c-6d28c5c457d4.PNG)

**Comment by dsblank** [comment]
Good to know you have a workaround; thanks for the update!

**Comment by peter73421** [comment]
Well, I want to use octave instead of python/opencv anyway... would be great to get it fix :)

**Comment by dsblank** [comment]
Running from nteract shows this warning (could be a clue):
![screenshot from 2017-04-29 08-07-14](https://cloud.githubusercontent.com/assets/168568/25555365/e5d4db7e-2cb2-11e7-946b-b5e53b2dc688.png)

**Comment by dsblank** [comment]
Which suggests this issue: http://wiki.octave.org/GraphicsMagick

**Comment by dsblank** [comment]
It doesn't look like there is anything we can do on our end.

**Comment by peter73421** [comment]
Hmm. Desktop octave app seems to work fine.

Dne 29. 4. 2017 2:33 odpoledne napsal uživatel "Doug Blank" <
notifications@github.com>:

It doesn't look like there is anything we can do on our end.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Calysto/octave_kernel/issues/86#issuecomment-298166347>,
or mute the thread

**Comment by peter73421** [comment]
Displaying color image after converting to "double" data type works ...

![capture](https://cloud.githubusercontent.com/assets/14235529/25567021/2700777e-2de5-11e7-9f42-3729c2b1d181.PNG)

**To grayscale**

![capture](https://cloud.githubusercontent.com/assets/14235529/25567024/3dcd344c-2de5-11e7-9258-6c5e54076e55.PNG)

**Change datatype of image to double**

![capture](https://cloud.githubusercontent.com/assets/14235529/25567032/707bb4c2-2de5-11e7-954f-ca9b30234524.PNG)

![capture](https://cloud.githubusercontent.com/assets/14235529/25567040/8ce3012e-2de5-11e7-9537-c0669db09949.PNG)

**Comment by zsef123** [comment]
I have problem too
![image](https://user-images.githubusercontent.com/18730255/30141240-011579ac-93b5-11e7-9f8a-53af4e821222.png)

**Comment by leolca** [comment]
The same issue reported by @ghost happens here. :-/
