### ISSUE TITLE
octave_kernel does not work with octave 4.0

### ISSUE THREAD

**Issue by simulkade** [Calysto/octave_kernel#9]
When I try to run octave_kernel in qtconsole or notebook, ipython opens the octave gui, which is enabled by default in octave 4.0.

**Comment by blink1073** [comment]
If you upgrade to `oct2py`` 3.2, you can set an `OCTAVE` environment variable to point to `octave-cli`.  Unfortunately this is the only way I know to support both the old and new versions of `Octave`.

**Comment by simulkade** [comment]
Thanks a lot Steven. I created a symbolic link to `octave-cli` and it works now.

**Comment by blink1073** [comment]
Also a valid method :smile:  I'm glad you're back on track.
