### ISSUE TITLE
Kernel sending status 'ok' with errors

### ISSUE THREAD

**Issue by JMurph2015** [Calysto/octave_kernel#93]
Hi!
I just noticed a pretty major standard non-compliance in your kernel today.
So when octave errors out, you should be sending back an execute-reply like this:
``` python
{
    #...
    'content':{
        'status':'error',
        'ename':<your_error_name>,
        'evalue':<your_error_data>,
        'traceback':<your_traceback>
    }
    #...
}
```
That way Jupyter can process that as a proper error and not just assume it is any old STDOUT.
Right now it would be a the easiest (?) fix to just rename what you are already returning to 'traceback' and insert some dummy values for the fields that you can't get easily.

It would be really awesome if this were fixed because it's breaking my use case!

**Comment by dsblank** [comment]
Issue being followed upstream: https://github.com/Calysto/metakernel/issues/149
