### ISSUE TITLE
subplot with imshow

### ISSUE THREAD

**Issue by zsef123** [Calysto/octave_kernel#97]
![image](https://user-images.githubusercontent.com/18730255/30164514-c9bb0784-9417-11e7-9c2e-e09bb021e611.png)

I want to 2 image horizontally like under cell.
But it's visible only when the image is like any other.

p.s. `imshow(lenna)` when single call, not visible image. So I convert to double type(`im2double`).
In above case, even though I did not do convert, I can see the image.

**Comment by blink1073** [comment]
Hi @zsef123, this comes from the way we are trying to intelligently determine what kind of plot to show [here](https://github.com/Calysto/octave_kernel/blob/master/octave_kernel/_make_figures.m#L95).  It looks like it could use some more work.
