### ISSUE TITLE
plot command and figure fail in octave 4.2.1_6

### ISSUE THREAD

**Issue by sunilshah** [Calysto/octave_kernel#98]
I am using octave 4.2.1_6 installed using homebrew on mac OSX 10.12.6.  From terminal command line, octave-cli plots  work fine with gnuplot using either qt or aquaterm.

However, using octave kernel in Jupyter notebook, it fails to plot.

plot(1:10)

no element found: line 1, column 0

figure(1)

Inline plot failed, consider trying another graphics toolkit
error: print: no axes object in figure to print
error: called from
    _make_figures>safe_print at line 122 column 7
    _make_figures at line 44 column 13

Strangely, on another Mac, the same setup works.

**Comment by blink1073** [comment]
Hi @sunilshah, the Octave support for `print()` is not as good as the live images.  Do both machines have the same version of `gnuplot`?

**Comment by sunilshah** [comment]
To clarify,  the errors reported are for getting live images using plot command.  

Are you referring, by any chance, to use of print()  in octave_kernel / _make_figures ? 

The failing Mc does use newest version of gnuplot - 5.2.0

The working version is using 5.0.6.

On the failing Mac, I some plots work in line.  Others do not.  I can not see a pattern.

However, if I do not use inline plots but instead insert magic 
%plot gnu plot
plot(1:10)

then the plots work fine as they appear in a separate window.

**Comment by blink1073** [comment]
Right, the inline plots are made in `_make_figures` using `print()` to get a static image.  The static image creation is what is not very well featured.

**Comment by zkokaja** [comment]
I also ran into this same issue on my Mac using gnuplot 5.2.2 and octave_kernel 0.28.2. The solution for me was to revert gnuplot to 5.0.6.

Using homebrew:
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/b69a5d2e8c8b8f954a8ea63d7327ebab0aac248c/Formula/gnuplot.rb`

**Comment by sunilshah** [comment]
What version of Mac OS are you running?  Did you need to reinstall octave from source?

**Comment by zkokaja** [comment]
I'm on 10.13.1, and no I didn't need to reinstall octave.

**Comment by matteo-V** [comment]
I'm running into trouble with this now. I'm trying to revert to Gnuplot 5.0.6 but I am having trouble. Anyone mind posting a guide for how they got their octave/jupyter working?

**Comment by dsblank** [comment]
@matteo-V What OS are you on?

**Comment by matteo-V** [comment]
@dsblank I'm in macOS 10.13.2 with Gnuplot 5.2

**Comment by wirawan0** [comment]
I am experiencing the same trouble. MacOS 10.11.6, GNUPlot 5.2.2 built with homebrew, Octave 4.2.1 (also homebrew), Anaconda 4.2.0 (python 2.7).

**Comment by sunilshah** [comment]
I am now on Mac OS 10.13.2,  gnuplot 5.2.2_1, octave 4.2.1_7, python3 3.6.3.  

%plot -f png generates inline plots of poorer quality.  %plot gnuplot does work in a separate window with high quality.

**Comment by DeepWalter** [comment]
`%plot -f svg` generates inline plots with much higher quality than `png` and `jpg`. But you must **supply each plot with a legend**. Otherwise, the `no element found` error will occur. I have no clue why this happens. 

My Env: macOS 10.12.6, octave 4.2.1(brew), gnuplot 5.2.2(brew), python 3.6.3(Anaconda), octave_kernel 0.28.2.

**Comment by sunilshah** [comment]
Thanks @DeepWalter.  It does help but I need to change all current notebooks.  

@dsblank,  how do you debug this python code?  Is there a more robust way to work around these problems using oct2py and using native python kernel for actual inline plots?

**Comment by blink1073** [comment]
The code that is producing the plots is an [m file](https://github.com/Calysto/octave_kernel/blob/master/octave_kernel/_make_figures.m).  The problem is that we need to get the plot image from Octave itself, but it does not have as robust methods of doing so as matplotlib.

**Comment by louy2** [comment]
Adding a legend as @DeepWalter said indeed displayed a plot image, but it is huge. Is there any way to control the size of the plot?

**Comment by dsblank** [comment]
@louy2 Did you use a legend with the svg form?

**Comment by louy2** [comment]
@dsblank I tried with and without, getting the same results. I think specifying size didn't resize the output but rather cropped the output.
